Repository yalla-coop/presspad, pull requests merged in 2019-06, with the labels that each got.

#78 Host profile
  client/package-lock.json
  client/src/assets/back-arrow.svg
  client/src/assets/listing-placeholder.jpg
  client/src/assets/random-profile.jpg
  client/src/assets/star-sign-symbol.svg
  client/src/components/Pages/HostCreateProfile/Content.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/theme.js
  package-lock.json
  server/__test__/api/getHostProfile.js
  server/__test__/database/queries/hostProfileData.js
  server/__test__/database/schema/listing.js
  server/__test__/database/schema/review.js
  server/controllers/hostsCompleteProfile.js
  server/controllers/profile/getHostProfile.js
  server/database/data/development/listings.js
  server/database/data/development/profiles.js
  server/database/data/development/reviews.js
  server/database/data/development/users.js
  server/database/models/Listing.js
  server/database/models/Profile.js
  server/database/queries/profile/hostProfile.js
  server/database/queries/profiles.js
  server/router/index.js
Labels: in-progress

#79 Sign up
  client/package-lock.json
  client/package.json
  client/src/components/Pages/Dashboard/index.js
  client/src/components/Pages/SignUpPage/SignUpPage.style.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  package-lock.json
  package.json
  server/__test__/api/user.getUserByReferral.js
  server/__test__/api/user.login.js
  server/__test__/api/user.signup.js
  server/__test__/database/queries/user.addNewUser.js
  server/controllers/user/getAllOrgs.js
  server/controllers/user/getUserByReferral.js
  server/controllers/user/signup.js
  server/database/data/development/index.js
  server/database/data/development/orgCodes.js
  server/database/data/development/organisations.js
  server/database/data/development/users.js
  server/database/data/test/index.js
  server/database/models/OrgCodes.js
  server/database/models/User.js
  server/database/queries/user/index.js
  server/database/queries/user/organisation.js
  server/router/index.js
Labels: awaiting-review

#85 Hosts Search Page
  client/package.json
  client/src/components/Pages/SearchHosts/SearchHosts.style.js
  client/src/components/Pages/SearchHosts/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  server/__test__/api/profile.searchProfiles.js
  server/__test__/database/queries/profile.searchProfiles.js
  server/controllers/profile/searchProfiles.js
  server/database/queries/profile/searchProfiles.js
  server/router/index.js
Labels: awaiting-review

#90 Admin view
  client/package-lock.json
  client/src/components/Pages/AdminDashboard/AdminDashboard.style.js
  client/src/components/Pages/AdminDashboard/ClientTable.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/SignInPage/index.js
  client/src/components/Pages/index.js
  client/src/components/test.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  client/src/helpers/getUserId.js
  client/src/theme.js
  package-lock.json
  server/__test__/api/stats.adminStats.js
  server/__test__/api/user.getUserByReferral.js
  server/__test__/database/queries/stats.getAllClientStats.js
  server/__test__/database/queries/stats.getAllHostStats.js
  server/__test__/database/queries/stats.getAllInternStats.js
  server/__test__/database/queries/user.getInternStatus.js
  server/__test__/database/schema/booking.js
  server/__test__/database/schema/transaction.js
  server/controllers/stats/adminStats.js
  server/database/data/development/bookings.js
  server/database/data/development/index.js
  server/database/data/development/transactions.js
  server/database/data/development/users.js
  server/database/data/test/index.js
  server/database/queries/stats/getAllClientStats.js
  server/database/queries/stats/getAllHostStats.js
  server/database/queries/stats/getAllInternStats.js
  server/database/queries/user/index.js
  server/router/index.js
Labels: awaiting-review, in-review

#95 Update schema
  server/__test__/api/stats.adminStats.js
  server/__test__/database/queries/stats.getAllClientStats.js
  server/controllers/stats/adminStats.js
  server/database/data/development/organisations.js
  server/database/data/development/transactions.js
  server/database/data/development/users.js
  server/database/data/test/organisations.js
  server/database/models/Organisation.js
  server/database/models/Transaction.js
  server/database/models/User.js
  server/database/queries/stats/getAllClientStats.js
Labels: awaiting-review

#88 Intern create profile
  client/src/components/Pages/HostCreateProfile/Content.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/InternCreateProfile.style.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  client/src/index.css
  server/constants.js
  server/controllers/hostsCompleteProfile.js
  server/controllers/user/internsCompleteProfile.js
  server/database/queries/user/index.js
  server/middlewares/deleteFromServer.js
  server/middlewares/googleStorage.js
  server/middlewares/multer.js
  server/router/index.js
Labels: awaiting-review

#96 Organisation dashboard
  client/package-lock.json
  client/src/assets/contact-icon.svg
  client/src/assets/home-icon.svg
  client/src/assets/invoice-icon.svg
  client/src/components/App.js
  client/src/components/Common/DisabledPopOver/DisabledPopOver.style.js
  client/src/components/Common/DisabledPopOver/index.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  client/src/components/Pages/Dashboard/index.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/InternColumns.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
  client/src/components/Pages/OrgDashboard/Update.js
  client/src/components/Pages/OrgDashboard/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/helpers.js
  client/src/theme.js
  package-lock.json
  server/__test__/api/org.dashboard.js
  server/__test__/api/stats.adminStats.js
  server/__test__/database/schema/notifications.js
  server/controllers/organisation/dashboard.js
  server/database/data/development/index.js
  server/database/data/development/notifications.js
  server/database/data/development/organisations.js
  server/database/data/development/users.js
  server/database/data/resetDB.js
  server/database/data/test/index.js
  server/database/data/test/notifications.js
  server/database/models/Notification.js
  server/database/models/User.js
  server/database/queries/organisation/dashboard.js
  server/database/queries/user/index.js
  server/database/queries/user/organisation.js
  server/router/index.js
Labels: awaiting-review

#97 Admin approve host profile
  client/src/components/Common/Button/index.js
  client/src/components/Pages/AdminDashboard/AdminDashboard.style.js
  client/src/components/Pages/AdminDashboard/ClientTable.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/HostProfile/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  server/__test__/api/profile.verifyProfile.js
  server/__test__/database/queries/profile.searchProfiles.js
  server/__test__/database/queries/profile.verifyProfile.js
  server/__test__/database/schema/listing.js
  server/__test__/database/schema/profile.js
  server/controllers/profile/verifyProfile.js
  server/controllers/stats/adminStats.js
  server/database/data/development/listings.js
  server/database/data/development/profiles.js
  server/database/data/test/listings.js
  server/database/data/test/profiles.js
  server/database/data/test/users.js
  server/database/queries/profile/verifyProfile.js
  server/database/queries/stats/getAllHostStats.js
  server/router/index.js
Labels: awaiting-review
