Repository yalla-coop/presspad, pull requests merged in 2019-08, with the labels that each got.

#121 110 refactor uploading mechanism
  client/src/components/Common/progress/ProgressBar.js
  client/src/components/Common/progress/ProgressBar.style.js
  client/src/components/Common/progress/ProgressRing.js
  client/src/components/Common/progress/index.js
  client/src/components/Pages/HostCreateProfile/Content.js
  client/src/components/Pages/HostCreateProfile/HostCreateProfile.style.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/InternCreateProfile.style.js
  client/src/components/Pages/InternCreateProfile/index.js
  server/controllers/hostsCompleteProfile.js
  server/database/queries/profiles.js
  server/helpers/storage.js
  server/middlewares/validation/hostProfileSchema.js
  server/middlewares/validation/index.js
  server/middlewares/validation/internProfileSchema.js
  server/router/index.js
Labels: awaiting-review

#152 Add "verified" badge only after successful hosting
  client/src/components/Pages/HostProfile/index.js
Labels: awaiting-review

#151 Landing Page Signup Links
  client/src/components/Pages/LandingPage/LandingPage.style.js
  client/src/components/Pages/LandingPage/index.js
Labels: awaiting-review

#119 User profile
  .eslintrc.json
  client/src/assets/.gitkeep
  client/src/components/Common/.gitkeep
  client/src/constants/apiRoutes.js
  package-lock.json
  package.json
  server/__test__/api/profile.getMyProfile.js
  server/controllers/.gitignore
  server/controllers/profile/getMyProfile.js
  server/database/data/development/profiles.js
  server/database/data/test/profiles.js
  server/database/queries/listing/getListing.js
  server/database/queries/profile/getProfile.js
  server/helpers/.gitkeep
  server/router/index.js
Labels: awaiting-review

#155 Sign out
  client/src/components/Common/Navbar/index.js
  client/src/constants/apiRoutes.js
  server/controllers/user/signOut.js
  server/router/index.js
Labels: awaiting-review

#167 Fix admin dashboard
  client/src/components/Common/Navbar/index.js
  client/src/components/Pages/AdminDashboard/ClientTable.js
Labels: awaiting-review, bug, urgent

#166 Intern dashboard
  client/src/assets/mapPin.svg
  client/src/components/Common/Calendar/Calendar.style.js
  client/src/components/Common/Calendar/index.js
  client/src/components/Common/Update/index.js
  client/src/components/Common/general/index.js
  client/src/components/Pages/Dashboard/index.js
  client/src/components/Pages/InternDashboard/BookingSection.js
  client/src/components/Pages/InternDashboard/InternDashboard.style.js
  client/src/components/Pages/InternDashboard/PaymentsSection.js
  client/src/components/Pages/InternDashboard/index.js
  client/src/constants/apiRoutes.js
  server/__test__/api/intern.dashboard.js
  server/controllers/dashboard/index.js
  server/controllers/dashboard/internDashboard.js
  server/database/queries/dashboard/index.js
  server/database/queries/dashboard/internDashboard.js
  server/router/index.js
Labels: awaiting-review

#169 Intern profile
  client/src/components/Pages/BookingRequest/index.js
  client/src/components/Pages/HostCreateProfile/Content.js
  client/src/components/Pages/HostCreateProfile/HostCreateProfile.style.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/InternCreateProfile.style.js
  client/src/components/Pages/InternProfile/BookingsColumns.js
  client/src/components/Pages/InternProfile/Content.js
  client/src/components/Pages/InternProfile/InternProfile.style.js
  client/src/components/Pages/InternProfile/index.js
  client/src/components/Pages/MyProfile/index.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  server/__test__/api/profile.getInternProfile.js
  server/__test__/api/reviews.js
  server/__test__/database/queries/internProfileData.js
  server/__test__/database/schema/review.js
  server/controllers/profile/getInternProfile.js
  server/controllers/profile/getMyProfile.js
  server/controllers/review/index.js
  server/database/data/development/reviews.js
  server/database/data/test/reviews.js
  server/database/models/Review.js
  server/database/queries/bookings/getInternBookingsWithReviews.js
  server/database/queries/bookings/index.js
  server/database/queries/profile/internProfile.js
  server/helpers/generateFileURL.js
  server/router/index.js
Labels: awaiting-review

#168 Sign up account
  client/src/components/App.js
  client/src/components/Common/Navbar/index.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/constants/navRoutes.js
  server/__test__/database/queries/user.addNewUser.js
  server/controllers/user/getUserByReferral.js
  server/controllers/user/internsCompleteProfile.js
  server/database/queries/profiles.js
  server/database/queries/user/index.js
  server/middlewares/validation/index.js
  server/middlewares/validation/internProfileSchema.js
Labels: awaiting-review

#170 Fix admin dashboard money
  client/src/components/Pages/AdminDashboard/AdminDashboard.style.js
  client/src/components/Pages/AdminDashboard/ClientTable.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  server/__test__/api/stats.adminStats.js
  server/__test__/database/queries/stats.getAllInternStats.js
  server/controllers/stats/adminStats.js
  server/database/queries/stats/getAllClientStats.js
  server/database/queries/stats/getAllHostStats.js
  server/database/queries/stats/getAllInternStats.js
Labels: awaiting-review

#171 Add review frontend
  client/src/components/Pages/AddReview/Avatar/AvatarStyle.js
  client/src/components/Pages/AddReview/Avatar/Message.js
  client/src/components/Pages/AddReview/Avatar/index.js
  client/src/components/Pages/AddReview/CallForReview/Text.js
  client/src/components/Pages/AddReview/CallForReview/Title.js
  client/src/components/Pages/AddReview/CallForReview/index.js
  client/src/components/Pages/AddReview/ReviewSection/ProfileForm/ImageSide.js
  client/src/components/Pages/AddReview/ReviewSection/ProfileForm/ProfileForm.style.js
  client/src/components/Pages/AddReview/ReviewSection/ProfileForm/ProfileInfo.js
  client/src/components/Pages/AddReview/ReviewSection/ProfileForm/index.js
  client/src/components/Pages/AddReview/ReviewSection/ReviewForm/ReviewFormHeaders.js
  client/src/components/Pages/AddReview/ReviewSection/ReviewForm/Styles.js
  client/src/components/Pages/AddReview/ReviewSection/ReviewForm/TextArea.js
  client/src/components/Pages/AddReview/ReviewSection/ReviewForm/index.js
  client/src/components/Pages/AddReview/ReviewSection/index.js
  client/src/components/Pages/AddReview/Wrappers/AvatarWrapper.js
  client/src/components/Pages/AddReview/Wrappers/ComponentWrapper.js
  client/src/components/Pages/AddReview/Wrappers/ImageWrapper.js
  client/src/components/Pages/AddReview/Wrappers/ProfileInfoWrapper.js
  client/src/components/Pages/AddReview/Wrappers/ProfileWrapper.js
  client/src/components/Pages/AddReview/Wrappers/ReviewFormWrapper.js
  client/src/components/Pages/AddReview/Wrappers/ReviewWrapper.js
  client/src/components/Pages/AddReview/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  server/__test__/api/reviews.js
  server/controllers/Bookings/index.js
  server/controllers/review/index.js
  server/database/queries/bookings/getBookingWithUsers.js
  server/database/queries/review/findReviewByBooking.js
  server/database/queries/review/index.js
  server/router/index.js
Labels: request-changes

#172 Edit profile
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/InternCreateProfile.style.js
  client/src/components/Pages/InternCreateProfile/Schema.js
  client/src/components/Pages/InternCreateProfile/index.js
  server/__test__/api/reviews.js
  server/__test__/api/stats.adminStats.js
  server/__test__/database/schema/profile.js
  server/controllers/profile/getMyProfile.js
  server/database/models/Profile.js
  server/middlewares/validation/index.js
  server/middlewares/validation/internProfileSchema.js
Labels: awaiting-review

#179 Test setup
  package.json
  server/__test__/api/getHostProfile.js
  server/__test__/api/intern.dashboard.js
  server/__test__/api/org.dashboard.js
  server/__test__/api/profile.getMyProfile.js
  server/__test__/api/reviews.js
  server/__test__/database/queries/bookings.js
  server/__test__/database/queries/user.getInternStatus.js
  server/__test__/database/queries/user.getUserReviews.js
  server/__test__/database/schema/booking.js
  server/__test__/database/schema/review.js
  server/app.js
  server/database/data/resetDB.js
  server/database/data/test/bookings.js
  server/database/data/test/checklistAnswers.js
  server/database/data/test/coupons.js
  server/database/data/test/externalTransactions.js
  server/database/data/test/index.js
  server/database/data/test/installments.js
  server/database/data/test/internalTransaction.js
  server/database/data/test/listings.js
  server/database/data/test/notifications.js
  server/database/data/test/orgCodes.js
  server/database/data/test/organisations.js
  server/database/data/test/profiles.js
  server/database/data/test/referrals.js
  server/database/data/test/reviews.js
  server/database/data/test/scheduledEmails.js
  server/database/data/test/scheduledNotifications.js
  server/database/data/test/transactions.js
  server/database/data/test/users.js
  server/database/dbConnection.js
  server/index.js
  testSetup.js
Labels: awaiting-review

#177 Host dashboard
  client/src/components/Common/BookingSection/InternDashboard.style.js
  client/src/components/Common/BookingSection/index.js
  client/src/components/Common/Button/index.js
  client/src/components/Common/Calendar/Calendar.style.js
  client/src/components/Common/Navbar/index.js
  client/src/components/Common/Update/index.js
  client/src/components/Pages/Dashboard/index.js
  client/src/components/Pages/HostCreateProfile/HostCreateProfile.style.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/HostDashboard.style.js
  client/src/components/Pages/HostDashboard/TablesColumns.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/HostDashboard/schemas.js
  client/src/components/Pages/InternDashboard/BookingSection.js
  client/src/components/Pages/InternDashboard/index.js
  client/src/constants/apiRoutes.js
  client/src/theme.js
  package.json
  server/__test__/api/payments/hostDonation.js
  server/__test__/api/payments/withdrawRequest.js
  server/__test__/api/user.login.js
  server/__test__/database/schema/withdrawRequests.js
  server/controllers/dashboard/hostDashboard.js
  server/controllers/dashboard/index.js
  server/controllers/dashboard/internDashboard.js
  server/controllers/payments/hostDonation.js
  server/controllers/payments/withdrawRequest.js
  server/database/data/development/index.js
  server/database/data/development/withdrawRequests.js
  server/database/data/test/index.js
  server/database/data/test/withdrawRequests.js
  server/database/dbConnection.js
  server/database/models/Account.js
  server/database/models/ExternalTransaction.js
  server/database/models/Installment.js
  server/database/models/InternalTransaction.js
  server/database/models/WithdrawRequest.js
  server/database/queries/dashboard/hostDashboard.js
  server/database/queries/dashboard/index.js
  server/database/queries/payments/hostDonateToPresspad.js
  server/database/queries/payments/hostRequestToWithdrawMoney.js
  server/database/queries/payments/index.js
  server/middlewares/validation/hostDashboard.js
  server/middlewares/validation/index.js
  server/router/index.js
Labels: awaiting-review

#182 Refactor organisations dashboard
  client/package-lock.json
  client/package.json
  client/src/components/Common/Button/index.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/CouponsColumns.js
  client/src/components/Pages/OrgDashboard/InternColumns.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
  client/src/components/Pages/OrgDashboard/index.js
  client/src/components/Pages/OrgDashboard/schema.js
  client/src/constants/apiRoutes.js
  client/src/helpers.js
  client/src/theme.js
  package-lock.json
  package.json
  server/__test__/api/org.dashboard.js
  server/__test__/api/payments/createCoupon.js
  server/__test__/database/schema/coupon.js
  server/controllers/coupons/createCoupon.js
  server/controllers/coupons/index.js
  server/controllers/organisation/dashboard.js
  server/controllers/profile/getInternProfile.js
  server/controllers/user/getAllInterns.js
  server/database/data/development/coupons.js
  server/database/data/test/coupons.js
  server/database/models/Coupon.js
  server/database/queries/organisation/dashboard.js
  server/database/queries/payments/createCoupon.js
  server/database/queries/payments/index.js
  server/database/queries/user/index.js
  server/helpers/payments.js
  server/middlewares/authentication.js
  server/router/index.js
Labels: awaiting-review

#174 Check for verified and complete intern profile + update host profile
  client/src/components/Common/Profile/ListingGallery.js
  client/src/components/Common/Profile/ListingGallery.style.js
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/Calendar.style.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/HostProfile/index.js
  client/src/constants/apiRoutes.js
  server/__test__/api/getHostProfile.js
  server/__test__/api/reviews.js
  server/__test__/database/queries/hostProfileData.js
  server/controllers/hostsCompleteProfile.js
  server/controllers/profile/getHostProfile.js
  server/controllers/profile/getInternStatus.js
  server/database/queries/listing/index.js
  server/database/queries/listings.js
  server/database/queries/profile/getProfile.js
  server/database/queries/profile/hostProfile.js
  server/database/queries/profiles.js
  server/helpers/isValidMongoObjectId.js
  server/middlewares/validation/hostProfileSchema.js
  server/middlewares/validation/index.js
  server/middlewares/validation/internCompleteProfileSchema.js
  server/router/index.js
Labels: awaiting-review
