Repository yalla-coop/presspad, pull requests merged in 2019-09, with the labels that each got.

#189 Fix edit profile
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/SignUpPage/index.js
Labels: awaiting-review

#181 Checklist cronjob
  package-lock.json
  package.json
  server/app.js
  server/database/queries/bookings/findBookings.js
  server/database/queries/checkList/findAllQuestions.js
  server/database/queries/checkList/findAnswersByBookingDate.js
  server/database/queries/checkList/index.js
  server/helpers/cronjobs/index.js
  server/helpers/cronjobs/mailCron/createMessage.js
  server/helpers/cronjobs/mailCron/htmlGenerator.js
  server/helpers/cronjobs/mailCron/index.js
  server/helpers/cronjobs/mailCron/mailChecklist.js
  server/helpers/dateHelper/index.js
  server/helpers/errorLogger/index.js
  server/helpers/mailHelper/index.js
  server/helpers/mailHelper/transporter.js
Labels: awaiting-review

#186 Admin: View Payment List
  client/src/components/Pages/AdminDashboard/AdminDashboard.style.js
  client/src/components/Pages/AdminDashboard/ClientTable.js
  client/src/components/Pages/AdminDashboard/PaymentsTable.js
  client/src/components/Pages/AdminDashboard/config.PaymentsTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/HostDashboard/schemas.js
  client/src/components/Pages/InternDashboard/PaymentsSection.js
  client/src/constants/apiRoutes.js
  package.json
  server/__test__/api/admin.viewWithdrawRequests.js
  server/__test__/api/payments/hostDonation.js
  server/__test__/api/payments/withdrawRequest.js
  server/__test__/database/schema/withdrawRequests.js
  server/controllers/payments/withdrawRequest.js
  server/controllers/withdrawRequests/index.js
  server/database/data/development/withdrawRequests.js
  server/database/data/test/withdrawRequests.js
  server/database/models/WithdrawRequest.js
  server/database/queries/payments/hostRequestToWithdrawMoney.js
  server/database/queries/withdrawRequest/findAllWithdrawRequests.js
  server/database/queries/withdrawRequest/index.js
  server/middlewares/validation/hostDashboard.js
  server/router/index.js
Labels: awaiting-review

#191 Host approve booking
  client/src/components/Common/BookingSection/index.js
  client/src/components/Common/Button/index.js
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/BookingRequest/index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/BookingsColumns.js
  client/src/components/Pages/InternProfile/AdminOrInternView/Content.js
  client/src/components/Pages/InternProfile/AdminOrInternView/InternProfile.style.js
  client/src/components/Pages/InternProfile/AdminOrInternView/index.js
  client/src/components/Pages/InternProfile/HostView/HostView.style.js
  client/src/components/Pages/InternProfile/HostView/index.js
  client/src/components/Pages/InternProfile/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  server/__test__/api/acceptBooking.js
  server/__test__/api/rejectBooking.js
  server/controllers/booking/acceptBooking.js
  server/controllers/booking/index.js
  server/controllers/booking/rejectBooking.js
  server/controllers/dashboard/hostDashboard.js
  server/controllers/profile/hostViewInternProfile.js
  server/database/models/Booking.js
  server/database/models/Notification.js
  server/database/queries/bookings/getNextPendingBooking.js
  server/database/queries/bookings/index.js
  server/router/index.js
Labels: awaiting-review

#194 Show no funds message
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
  client/src/components/Pages/OrgDashboard/index.js
  server/database/queries/payments/createCoupon.js
Labels: awaiting-review, question

#203 refactor: add confirmDate for booking
  client/src/components/Pages/HostDashboard/TablesColumns.js
  server/database/data/test/bookings.js
  server/database/models/Booking.js
  server/database/queries/bookings/index.js
Labels: awaiting-review, refactor

#199 ADMIN: searchBar component
  client/package-lock.json
  client/package.json
  client/src/components/Common/SearchBar/index.js
  client/src/components/Pages/AdminDashboard/ClientTable.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  client/src/components/Pages/AdminDashboard/PaymentsTable.js
  client/src/components/Pages/AdminDashboard/config.PaymentsTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/helpers.js
  client/src/theme.js
  server/controllers/stats/adminStats.js
Labels: awaiting-review

#200 Edit host profile
  client/src/components/Pages/HostCreateProfile/Content.js
  client/src/components/Pages/HostCreateProfile/helpers.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/Calendar.style.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/MyProfile/index.js
  server/controllers/profile/getHostProfile.js
  server/controllers/profile/getMyProfile.js
  server/database/models/Listing.js
  server/database/models/Profile.js
  server/database/queries/profile/hostProfile.js
  server/middlewares/validation/hostProfileSchema.js
Labels: awaiting-review

#201 Transer cancel withdraw admin
  client/src/components/Pages/AdminDashboard/PaymentsTable.js
  client/src/components/Pages/AdminDashboard/config.PaymentsTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/constants/apiRoutes.js
  server/controllers/payments/index.js
  server/controllers/payments/withdrawRequest.js
  server/database/queries/payments/index.js
  server/database/queries/payments/withdrawRequests.js
  server/router/index.js
Labels: awaiting-review

#205 Refactor: block 7day after today when booking request
  client/src/components/Pages/HostProfile/Calendar.js
  server/__test__/api/newBooking.js
  server/controllers/booking/newBookingRequest.js
Labels: awaiting-review, refactor

#207 Send emails
  server/config.js
  server/controllers/booking/acceptBooking.js
  server/controllers/booking/rejectBooking.js
  server/controllers/profile/verifyProfile.js
  server/database/queries/bookings/index.js
  server/database/queries/profile/getProfile.js
  server/helpers/general.js
  server/helpers/mailHelper/profileApprovedToHost.js
  server/helpers/mailHelper/requestAcceptedToAdmin.js
  server/helpers/mailHelper/requestAcceptedToIntern.js
  server/helpers/mailHelper/requestRejectedToIntern.js
  server/helpers/mailHelper/transporter.js
Labels: awaiting-review

#208 delete listing photo
  client/src/components/Common/progress/ProgressBar.js
  client/src/components/Pages/HostCreateProfile/Content.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/index.js
  server/controllers/hostsCompleteProfile.js
  server/controllers/profile/deletListingPhotos.js
  server/database/queries/listing/index.js
  server/router/index.js
Labels: awaiting-review

#214 fix intern status bug
  server/database/queries/stats/getAllInternStats.js
Labels: awaiting-review

#211 fix different issues
  client/package-lock.json
  client/package.json
  client/src/components/Common/NotFound/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/index.js
Labels: awaiting-review

#217 Fix getting next booking
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/InternDashboard/BookingSection.js
  client/src/components/Pages/InternDashboard/index.js
  server/__test__/api/intern.dashboard.js
  server/controllers/dashboard/hostDashboard.js
  server/controllers/dashboard/internDashboard.js
  server/database/queries/bookings/getHostNextBooking.js
  server/database/queries/bookings/getInternNextBooking.js
  server/database/queries/bookings/index.js
Labels: awaiting-review

#218 refactor host search
  client/src/components/Pages/SearchHosts/index.js
  client/src/constants/apiRoutes.js
  server/controllers/listing/index.js
  server/database/queries/listing/index.js
  server/database/queries/profile/searchProfiles.js
  server/router/index.js
Labels: awaiting-review

#220 fix intern role in dashboard
  client/src/components/Pages/InternDashboard/BookingSection.js
  client/src/components/Pages/InternDashboard/index.js
Labels: awaiting-review
