Repository yalla-coop/presspad, pull requests merged in 2020-04, with the labels that each got.

#515 Payments tests
  package.json
  server/.eslintrc.js
  server/__mocks__/stripe.js
  server/__test__/api/dashboard/host.js
  server/__test__/api/internPayments/mockData.js
  server/__test__/api/internPayments/payFirstInstallment.js
  server/__test__/api/internPayments/payOldInstallment.js
  server/__test__/api/internPayments/payUpfront.js
  server/__test__/api/orgPaymentsAndCoupons/addFunds.js
  server/__test__/api/orgPaymentsAndCoupons/createCoupon.js
  server/__test__/api/otherPayments/hostDonation.js
  server/__test__/api/otherPayments/withdrawRequest.js
  server/__test__/api/payments/createCoupon.js
  server/__test__/api/payments/hostDonation.js
  server/__test__/api/payments/withdrawRequest.js
  server/controllers/payments/withdrawRequest.js
  server/database/data/test/withdrawRequests.js
  server/database/queries/payments/withdrawRequests.js
  server/database/testConnection.js
Labels: awaiting-review

#553 update DB schema
  client/src/components/Common/ProfileComponents/OtherInformationDetails/index.js
  client/src/components/Pages/InternCreateProfile/Schema.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/AdminView.js
  client/src/constants/fields.js
  server/database/data/test/profiles.js
  server/database/data/test/users.js
  server/database/models/Booking.js
  server/database/models/Profile.js
  server/database/models/User.js
  server/middlewares/validation/internCompleteProfileSchema.js
  server/middlewares/validation/internProfileSchema.js
Labels: awaiting-review

#555 542 create common layouts
  client/.eslintrc.js
  client/.storybook/main.js
  client/.storybook/preview-head.html
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/HOCs/index.js
  client/src/HOCs/withWindowWidth.js
  client/src/components/App.js
  client/src/components/Common/FooterNew/index.js
  client/src/components/Common/FooterNew/style.js
  client/src/components/Common/GoBack/index.js
  client/src/components/Common/GoBack/style.js
  client/src/components/Common/Icon/Arrow.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/Navbar/index.js
  client/src/components/Common/PrivateRoute/index.js
  client/src/components/Common/Route/index.js
  client/src/components/Common/SideMenu/index.js
  client/src/components/Common/SideMenu/style.js
  client/src/components/Common/Typography/index.js
  client/src/components/Common/Typography/style.js
  client/src/components/Layouts/GeneralLayout/index.js
  client/src/components/Layouts/SideMenuLayout/index.js
  client/src/components/Layouts/SideMenuLayout/style.js
  client/src/components/Layouts/index.js
  client/src/components/Pages/SearchHosts/SearchHosts.style.js
  client/src/components/Pages/index.js
  client/src/stories/0-Welcome.stories.js
  client/src/stories/1-Button.stories.js
  client/src/stories/2-Layouts.SideMenuLayout.stories.js
  client/src/stories/3-Typography.stories.js
  client/src/stories/4-GoBack.stories.js
  client/src/theme.js
Labels: awaiting-review

#557 Customize antd theme
  client/.storybook/main.js
  client/.storybook/preview.js
  client/config-overrides.js
  client/package-lock.json
  client/package.json
  client/src/components/App.js
  client/src/components/Common/Footer/Footer.style.js
  client/src/components/Pages/BookingView/HostView/InternInfo.js
  client/src/components/Pages/BookingView/HostView/index.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/HostProfile/old_index.js
  client/src/components/Pages/InternProfile/HostView/index.js
  client/src/components/Pages/ThemeTest.js
  client/src/components/Pages/index.js
  client/src/index.css
  client/src/stories/0-Welcome.stories.js
  client/src/stories/0-theme.stories.js
  client/theme-vars.less
  package-lock.json
Labels: awaiting-review

#558 Create common buttons
  client/src/components/Common/ButtonNew/index.js
  client/src/components/Common/Typography/style.js
  client/src/stories/1-Button.stories.js
  client/src/stories/3-Typography.stories.js
  client/src/theme.js
Labels: awaiting-review

#560 528 update search page
  client/src/assets/search-background.png
  client/src/components/Common/AntdWrappers/DatePicker.js
  client/src/components/Common/AntdWrappers/Modal.js
  client/src/components/Common/AntdWrappers/Select.js
  client/src/components/Common/AntdWrappers/Switch.js
  client/src/components/Common/AntdWrappers/index.js
  client/src/components/Common/AntdWrappers/style.js
  client/src/components/Common/Typography/index.js
  client/src/components/Common/Typography/style.js
  client/src/components/Layouts/GeneralLayout/index.js
  client/src/components/Layouts/GeneralLayout/style.js
  client/src/components/Layouts/SideMenuLayout/style.js
  client/src/components/Pages/SearchHosts/Form.js
  client/src/components/Pages/SearchHosts/Hero.js
  client/src/components/Pages/SearchHosts/HostCard.js
  client/src/components/Pages/SearchHosts/Hosts.js
  client/src/components/Pages/SearchHosts/NoResults.js
  client/src/components/Pages/SearchHosts/SearchHosts.style.js
  client/src/components/Pages/SearchHosts/index.js
  client/src/components/Pages/SearchHosts/style.js
  client/src/components/Pages/SearchHosts/utils.js
  client/src/components/Pages/ThemeTest.js
  client/src/helpers.js
  client/src/index.css
  client/src/stories/0-Welcome.stories.js
  client/src/stories/6-HostCard.stories.js
  client/theme-vars.less
  server/controllers/profile/searchProfiles.js
  server/database/queries/profile/searchProfiles.js
Labels: request-changes

#559 531 admin review
  client/src/components/Pages/AdminDashboard/AdminDashboard.style.js
  client/src/components/Pages/AdminDashboard/Bookings/ExpandedDetails.js
  client/src/components/Pages/AdminDashboard/Bookings/columns.js
  client/src/components/Pages/AdminDashboard/Bookings/index.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/HostProfile/old_index.js
  client/src/components/Pages/InternDashboard/TablesColumns.js
  client/src/constants/apiRoutes.js
  client/src/index.css
  client/src/theme.js
  server/__test__/api/bookings/adminReviewsBooking.js
  server/__test__/api/bookings/getActiveBookings.js
  server/__test__/api/bookings/getBookingHistory.js
  server/__test__/api/bookings/newRequest.js
  server/__test__/api/dashboard/host.js
  server/__test__/api/dashboard/intern.js
  server/__test__/database/queries/bookings/bookings.js
  server/app.js
  server/controllers/booking/adminReviewsBooking.js
  server/controllers/booking/getActiveBookings.js
  server/controllers/booking/getBookingHistory.js
  server/controllers/booking/index.js
  server/controllers/booking/newBookingRequest.js
  server/controllers/dashboard/hostDashboard.js
  server/controllers/payments/intern.js
  server/controllers/stats/adminStats.js
  server/database/data/test/bookings.js
  server/database/data/test/index.js
  server/database/data/test/listings.js
  server/database/models/Booking.js
  server/database/models/Notification.js
  server/database/queries/bookings/getActiveBookings.js
  server/database/queries/bookings/getBookingHistory.js
  server/database/queries/bookings/index.js
  server/database/queries/dashboard/hostDashboard.js
  server/router/index.js
Labels: awaiting-review

#561 Intern booking detail
  client/package-lock.json
  client/package.json
  client/src/assets/tips-star.svg
  client/src/components/Common/ButtonNew/index.js
  client/src/components/Common/Icon/icons/QuestionMark.js
  client/src/components/Common/Icon/index.js
  client/src/components/Pages/BookingView/BookingDates/BookingDates.style.js
  client/src/components/Pages/BookingView/BookingDates/index.js
  client/src/components/Pages/BookingView/CancelBookingButton/index.js
  client/src/components/Pages/BookingView/HostInternInfo/HostInternInfo.style.js
  client/src/components/Pages/BookingView/HostInternInfo/index.js
  client/src/components/Pages/BookingView/InternView/InternView.style.js
  client/src/components/Pages/BookingView/InternView/MakePayment/CodeLoading.js
  client/src/components/Pages/BookingView/InternView/MakePayment/MakePayment.style.js
  client/src/components/Pages/BookingView/InternView/MakePayment/index.js
  client/src/components/Pages/BookingView/InternView/ReportProblem/ReportProblem.style.js
  client/src/components/Pages/BookingView/InternView/ReportProblem/index.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/BookingView/InternView/statusContents.js
  client/src/components/Pages/BookingView/LeaveReview/LeaveReview.style.js
  client/src/components/Pages/BookingView/LeaveReview/index.js
  client/src/components/Pages/BookingView/TipsCard/TipsCard.style.js
  client/src/components/Pages/BookingView/TipsCard/index.js
  client/src/components/Pages/index.js
  client/src/constants/errorMessages.js
  client/src/theme.js
  client/theme-vars.less
  server/controllers/profile/getHostProfile.js
  server/controllers/review/postReview.js
  server/database/queries/bookings/getBooking.js
  server/database/queries/profile/hostProfile.js
Labels: awaiting-review

#568 529 host profile updates
  client/package-lock.json
  client/src/components/Common/ButtonNew/index.js
  client/src/components/Common/CouponCode/index.js
  client/src/components/Common/Icon/icons/Close.js
  client/src/components/Common/Icon/icons/QuestionCircle.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/Profile/ListingGallery.js
  client/src/components/Common/Profile/ListingGallery.style.js
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Common/Reviews/Review.js
  client/src/components/Common/Reviews/Reviews.style.js
  client/src/components/Common/Reviews/index.js
  client/src/components/Common/Typography/style.js
  client/src/components/Layouts/SideMenuLayout/index.js
  client/src/components/Pages/BookingView/InternView/CouponCode.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/Calendar.style.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/HostProfile/InternOrgView/AccommodationCheckList.js
  client/src/components/Pages/HostProfile/InternOrgView/Card.js
  client/src/components/Pages/HostProfile/InternOrgView/Header.js
  client/src/components/Pages/HostProfile/InternOrgView/HostProfileCalendar.js
  client/src/components/Pages/HostProfile/InternOrgView/index.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/HostProfile/utils.js
  client/src/components/Pages/SearchHosts/HostCard.js
  client/src/constants/types.js
  client/src/helpers.js
  client/src/theme.js
  package-lock.json
  server/__test__/api/bookings/newRequest.js
  server/__test__/api/orgPaymentsAndCoupons/createCoupon.js
  server/controllers/booking/newBookingRequest.js
  server/controllers/coupons/createCoupon.js
  server/controllers/profile/getHostProfile.js
  server/database/constants.js
  server/database/data/test/coupons.js
  server/database/data/test/index.js
  server/database/data/test/listings.js
  server/database/data/test/profiles.js
  server/database/models/Profile.js
  server/database/queries/profile/hostProfile.js
  server/helpers/payments.js
Labels: awaiting-review

#569 530 internship details check
  client/src/components/Common/AntdWrappers/DatePicker.js
  client/src/components/Common/AntdWrappers/Input.js
  client/src/components/Common/AntdWrappers/Modal.js
  client/src/components/Common/AntdWrappers/index.js
  client/src/components/Common/AntdWrappers/style.js
  client/src/components/Common/ProfileComponents/Field/DatePicker.js
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Common/ProfileComponents/OtherInformationDetails/index.js
  client/src/components/Pages/HostCreateProfile/Schema.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/InternCreateProfile/Schema.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/SearchHosts/Form.js
  client/src/components/Pages/SearchHosts/index.js
  client/src/components/Pages/SearchHosts/utils.js
  client/src/components/Pages/UpdateInternship/Form.js
  client/src/components/Pages/UpdateInternship/index.js
  client/src/components/Pages/UpdateInternship/style.js
  client/src/components/Pages/UpdateInternship/utils.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/errorMessages.js
  client/src/constants/fields.js
  client/src/constants/navRoutes.js
  client/src/helpers.js
  client/src/helpers/sendBookingRequest.js
  client/src/index.css
  client/src/theme.js
  client/src/validation/index.js
  client/src/validation/internship.js
  server/__test__/helpers/checkInternshipDates.js
  server/app.js
  server/controllers/booking/newBookingRequest.js
  server/controllers/profile/getInternStatus.js
  server/controllers/profile/getInternshipDetails.js
  server/controllers/profile/updateInternshipDetails.js
  server/database/queries/profile/getInternshipDetails.js
  server/helpers/general.js
  server/middlewares/validation/internCompleteProfileSchema.js
  server/middlewares/validation/internProfileSchema.js
  server/middlewares/validation/validation2.js
  server/router/index.js
Labels: awaiting-review, request-changes

#565 Host booking details
  client/src/assets/fireworks.png
  client/src/components/Common/Typography/style.js
  client/src/components/Pages/BookingView/HostInternInfo/HostInternInfo.style.js
  client/src/components/Pages/BookingView/HostInternInfo/index.js
  client/src/components/Pages/BookingView/HostView/HostView.style.js
  client/src/components/Pages/BookingView/HostView/WarningModal.js
  client/src/components/Pages/BookingView/HostView/index.js
  client/src/components/Pages/BookingView/HostView/reducer.js
  client/src/components/Pages/BookingView/HostView/statusContents.js
  client/src/components/Pages/BookingView/InternView/ReportProblem/ReportProblem.style.js
  client/src/components/Pages/BookingView/InternView/ReportProblem/index.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/BookingView/LeaveReview/index.js
  client/src/components/Pages/HostDashboard/TablesColumns.js
  client/src/constants/errorMessages.js
  server/__test__/api/bookings/accept.js
  server/__test__/api/bookings/reject.js
  server/__test__/database/queries/bookings/getOverlappingBookings.js
  server/controllers/booking/acceptBooking.js
  server/controllers/booking/rejectBooking.js
  server/controllers/profile/hostViewInternProfile.js
  server/controllers/review/postReview.js
  server/database/queries/bookings/getBooking.js
  server/database/queries/bookings/getBookingsDetails.js
  server/database/queries/bookings/getOverlappingBookings.js
  server/database/queries/bookings/index.js
  server/database/queries/profile/internProfileBookingView.js
  server/database/queries/user/index.js
  server/database/queries/user/updateRespondingData.js
  server/services/bookings/index.js
  server/services/bookings/rejectBookings.js
Labels: awaiting-review

#587 Update host response time
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/InternOrgView/HostProfileCalendar.js
  client/src/components/Pages/HostProfile/InternOrgView/index.js
  client/src/helpers.js
  server/__test__/api/bookings/accept.js
  server/__test__/api/bookings/reject.js
  server/controllers/booking/acceptBooking.js
  server/controllers/booking/rejectBooking.js
  server/database/models/Booking.js
  server/database/queries/bookings/index.js
  server/database/queries/profile/hostProfile.js
  server/services/bookings/rejectBookings.js
Labels: awaiting-review

#563 535 - Add DBS flow
  .DS_Store
  client/.eslintrc.js
  client/src/assets/presspad-logo.png
  client/src/components/Common/Files/FileDownload.js
  client/src/components/Common/ProfileComponents/AboutYouDetails/index.js
  client/src/components/Common/ProfileComponents/DBSCheck.js
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Common/ProfileComponents/OtherInformationDetails/index.js
  client/src/components/Common/ProfileComponents/ProfileComponents.style.js
  client/src/components/Common/ProfileComponents/index.js
  client/src/components/Common/Typography/index.js
  client/src/components/Common/Typography/style.js
  client/src/components/Layouts/RightDivLayout/index.js
  client/src/components/Layouts/RightDivLayout/style.js
  client/src/components/Layouts/index.js
  client/src/components/Pages/AdminDashboard/AdminDashboard.style.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/DBSCheck/Page1.js
  client/src/components/Pages/DBSCheck/Page2.js
  client/src/components/Pages/DBSCheck/index.js
  client/src/components/Pages/DBSCheck/style.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/AboutYouDetails/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/Details/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/OtherInformation/index.js
  client/src/components/Pages/HostCreateProfile/Schema.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/HostProfile/AdminView.js
  client/src/components/Pages/HostProfile/HostView.js
  client/src/components/Pages/HostProfile/old_index.js
  client/src/components/Pages/InternCreateProfile/Schema.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/AdminView.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/externalLinks.js
  client/src/constants/fields.js
  client/src/constants/navRoutes.js
  client/src/stories/3-Typography.stories.js
  client/src/stories/6-Layouts.RightDivLayout.stories.js
  client/src/theme.js
  server/__test__/api/profiles/updateProfile.js
  server/controllers/hostsCompleteProfile.js
  server/controllers/profile/updateProfile.js
  server/controllers/stats/adminStats.js
  server/database/data/test/profiles.js
  server/database/models/Profile.js
  server/database/queries/dashboard/internDashboard.js
  server/database/queries/profiles.js
  server/database/queries/stats/getAllHostStats.js
  server/database/queries/stats/getAllInternStats.js
  server/middlewares/validation/hostProfileSchema.js
  server/middlewares/validation/internCompleteProfileSchema.js
  server/middlewares/validation/internProfileSchema.js
  server/router/index.js
Labels: awaiting-review

#584 Fix update booking bug
  client/src/components/Pages/AdminDashboard/index.js
Labels: awaiting-review

#586 570 show bookingdetails internship
  client/src/components/Common/BookingDetailsBox/BookingDetails.style.js
  client/src/components/Common/BookingDetailsBox/index.js
  client/src/components/Common/ButtonNew/index.js
  client/src/components/Common/ScrollToTop/index.js
  client/src/components/Pages/BookingView/HostView/index.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/UpdateInternship/Form.js
  client/src/components/Pages/UpdateInternship/index.js
  client/src/components/Pages/UpdateInternship/style.js
Labels: awaiting-review

#594 588 fix
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/index.js
  server/__test__/api/bookings/adminReviewsBooking.js
  server/__test__/api/bookings/getActiveBookings.js
  server/__test__/api/dashboard/intern.js
  server/controllers/booking/adminReviewsBooking.js
  server/database/data/test/bookings.js
  server/database/data/test/profiles.js
  server/database/data/test/users.js
  server/database/models/Notification.js
Labels: awaiting-review
