Repository yalla-coop/presspad, pull requests merged in 2020-08, with the labels that each got.

#715 644 create banners component
  client/package-lock.json
  client/package.json
  client/src/components/App.js
  client/src/components/Common/CookiesBannar/index.js
  client/src/components/Common/CookiesBannar/style.css
  client/src/components/Common/CookiesBannar/style.js
  client/src/components/Common/Notification/index.js
  client/src/components/Common/Notification/style.css
  client/src/index.css
  client/src/stories/15-Cookies.stories.js
  client/src/stories/Notifiaction.stories.js
Labels: awaiting-review

#716 646 faq component
  client/src/components/Common/FAQ/index.js
  client/src/components/Common/FAQ/style.js
  client/src/components/Common/Icon/icons/Arrow.js
  client/src/stories/9-FAQ.stories.js
Labels: awaiting-review

#714 add updates for cancelling flow
  client/src/components/Common/Update/index.js
  client/src/components/Pages/OrgDashboard/Update.js
  server/controllers/booking/cancelBooking.js
  server/controllers/payments/cancelBookingAfterPayment.js
  server/controllers/payments/intern.js
  server/database/models/Installment.js
  server/database/models/Notification.js
  server/database/queries/ScheduledEmail/getOutstandingPaymentReminders.js
  server/helpers/cronjobs/automaticCancellation/index.js
  server/services/mailing/schedulePaymentReminders.js
  server/services/mailing/sendOutstandingPaymentReminders.js
Labels: awaiting-review

#718 647 create link component
  client/src/components/Common/Icon/icons/AlertTriangle.js
  client/src/components/Common/Icon/icons/Copy.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/LinkCopy/index.js
  client/src/stories/16-CopyLink.stories.js
Labels: awaiting-review

#717 659 delete account
  client/src/components/Common/Route/index.js
  client/src/components/Layouts/IllustrationsLayout/index.js
  client/src/components/Layouts/IllustrationsLayout/style.js
  client/src/components/Pages/Settings/DeleteAccountSuccess.js
  client/src/components/Pages/Settings/index.js
  client/src/components/Pages/Settings/style.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  client/src/stories/8-Layouts.Illustrations.stories.js
  server/config.js
  server/controllers/user/deleteAccount.js
  server/database/models/User.js
  server/database/queries/profiles.js
  server/database/queries/user/index.js
  server/pubSub/eventTypes.js
  server/pubSub/user.js
  server/router/index.js
  server/services/mailing/accountDeleted.js
  server/services/mailing/index.js
  server/services/mailing/templates/admin/index.js
  server/services/mailing/templates/admin/userDeletedAccount.js
  server/services/mailing/templates/mailsTypes.js
Labels: awaiting-review

#719 684 inputs
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/components/Common/AntdWrappers/DatePicker.js
  client/src/components/Common/AntdWrappers/Input.js
  client/src/components/Common/AntdWrappers/Select.js
  client/src/components/Common/AntdWrappers/index.js
  client/src/components/Common/AntdWrappers/style.js
  client/src/components/Common/Icon/icons/Calendar.js
  client/src/components/Common/Icon/icons/Chevron.js
  client/src/components/Common/Icon/icons/UploadFile.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/Inputs/Checkbox.js
  client/src/components/Common/Inputs/DatePicker.js
  client/src/components/Common/Inputs/InfoSection.js
  client/src/components/Common/Inputs/Input.js
  client/src/components/Common/Inputs/Select.js
  client/src/components/Common/Inputs/Switch.js
  client/src/components/Common/Inputs/UploadFile.js
  client/src/components/Common/Inputs/index.js
  client/src/components/Common/Inputs/input.stories.js
  client/src/components/Common/Inputs/style.js
  client/src/components/Common/Modal/index.js
  client/src/components/Pages/AdminDashboard/Bookings/BookingView/AdminActions.js
  client/src/components/Pages/SearchHosts/Form.js
  client/src/components/Pages/SearchHosts/utils.js
  client/src/components/Pages/ThemeTest.js
  client/src/components/Pages/UpdateInternship/Form.js
  client/src/components/Pages/UpdateInternship/utils.js
  client/src/helpers/sendBookingRequest.js
  client/src/theme.js
Labels: request-changes

#720 652 section (partial)
  client/src/assets/Illustrations/flower.svg
  client/src/components/Common/Cards/style.js
  client/src/components/Common/Icon/icons/Ambassador.js
  client/src/components/Common/Icon/icons/Community.js
  client/src/components/Common/Icon/icons/Flower.js
  client/src/components/Common/Icon/icons/Hearts.js
  client/src/components/Common/Icon/icons/QuestionCircle.js
  client/src/components/Common/Icon/icons/Star.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/Section/AccountDetails.js
  client/src/components/Common/Section/Badges.js
  client/src/components/Common/Section/Community.js
  client/src/components/Common/Section/InternshipDetails.js
  client/src/components/Common/Section/MyAccount.js
  client/src/components/Common/Section/MyImpact.js
  client/src/components/Common/Section/Reviews.js
  client/src/components/Common/Section/Updates/SingleUpdate.js
  client/src/components/Common/Section/Updates/index.js
  client/src/components/Common/Section/Wallet.js
  client/src/components/Common/Section/index.js
  client/src/components/Common/Section/index.stories.js
  client/src/components/Common/Section/style.js
  client/src/components/Common/Typography/index.js
  client/src/components/Common/Update/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/InternDashboard/index.js
  client/src/constants/externalLinks.js
  client/src/constants/navRoutes.js
  client/src/helpers.js
  client/src/helpers/formatPrice.js
  client/src/theme.js
Labels: awaiting-review

#722 Add Dashboard Booking Dates section > #651
  client/src/components/Common/ButtonNew/index.js
  client/src/components/Common/Cards/BookingCards.js
  client/src/components/Common/DashboardBookingDates/index.js
  client/src/components/Common/DashboardBookingDates/index.stories.js
  client/src/components/Common/DashboardBookingDates/style.js
  client/src/components/Common/Inputs/DatePicker.js
  client/src/components/Common/Inputs/input.stories.js
  client/src/components/Common/LinkButton/index.js
  client/src/components/Common/Title/index.js
  client/src/components/Common/Typography/style.js
Labels: awaiting-review

#721 672 referral schema
  client/package-lock.json
  client/package.json
  client/src/assets/referral.png
  client/src/components/Common/Grid/style.js
  client/src/components/Common/Icon/icons/Email.js
  client/src/components/Common/Icon/icons/Whatsapp.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/LinkCopy/index.js
  client/src/components/Common/Reviews/Reviews.style.js
  client/src/components/Common/Section/Badges.js
  client/src/components/Common/Typography/style.js
  client/src/components/Layouts/IllustrationsLayout/style.js
  client/src/components/Layouts/RightDivLayout/style.js
  client/src/components/Layouts/SideMenuLayout/style.js
  client/src/components/Pages/HostProfile/InternOrgView/index.js
  client/src/components/Pages/ReferralSchema/SocialShare.js
  client/src/components/Pages/ReferralSchema/index.js
  client/src/components/Pages/ReferralSchema/style.js
  client/src/components/Pages/SignUpPage/SignUp.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/components/Pages/index.js
  client/src/constants/navRoutes.js
  client/src/helpers/margins.js
  client/src/theme.js
  client/src/validation/signup.js
  package-lock.json
  package.json
  server/controllers/user/signup.js
  server/controllers/user/userInfo.js
  server/database/data/test/users.js
  server/database/models/User.js
  server/database/queries/profile/hostProfile.js
  server/database/queries/user/index.js
Labels: awaiting-review

#724 654 update menu
  client/src/components/Common/Navigation/Menu.js
  client/src/components/Common/Navigation/Menu.style.js
  client/src/constants/navRoutes.js
Labels: awaiting-review

#729 649 - Create Table Component
  client/src/components/Common/Files/FileDownload.js
  client/src/components/Common/SearchBar/index.js
  client/src/components/Common/Table/Common/DBSCol.js
  client/src/components/Common/Table/Common/DropdownCol.js
  client/src/components/Common/Table/Common/HouseViewingCol.js
  client/src/components/Common/Table/Common/InputCol.js
  client/src/components/Common/Table/Common/LinkCol.js
  client/src/components/Common/Table/Common/PayButtonCol.js
  client/src/components/Common/Table/Common/StandardCol.js
  client/src/components/Common/Table/Common/TagCol.js
  client/src/components/Common/Table/Common/index.js
  client/src/components/Common/Table/index.js
  client/src/components/Common/Table/index.stories.js
  client/src/components/Common/Table/style.js
  client/src/constants/navRoutes.js
  client/src/constants/statusTypes.js
  client/src/helpers.js
  client/src/helpers/camelToWords.js
Labels: awaiting-review

#731 Component fix
  client/src/components/Common/Icon/icons/Arrow2.js
  client/src/components/Common/Section/Payments.js
  client/src/components/Common/Section/Updates/SingleUpdate.js
  client/src/components/Common/Section/index.js
  client/src/components/Common/Section/index.stories.js
  client/src/components/Common/Section/style.js
  client/src/components/Common/Table/Common/BoldDateCol.js
  client/src/components/Common/Table/Common/PayButtonCol.js
  client/src/components/Common/Table/Common/TagCol.js
  client/src/components/Common/Table/Common/index.js
  client/src/components/Common/Table/index.js
  client/src/components/Common/Table/style.js
  client/src/constants/statusTypes.js
  client/src/helpers/formatPrice.js
  client/src/helpers/margins.js
  package-lock.json
  package.json
Labels: awaiting-review

#728 669 host dashboard updates
  client/src/assets/heart.svg
  client/src/components/Common/Cards/BookingCards.js
  client/src/components/Common/Cards/style.js
  client/src/components/Common/DashboardBookingDates/index.js
  client/src/components/Common/DashboardBookingDates/validateAvailabiltySchema.js
  client/src/components/Common/Grid/style.js
  client/src/components/Common/Icon/icons/ExplanationMarkCircle.js
  client/src/components/Common/Icon/icons/Flower.js
  client/src/components/Common/Icon/icons/Money.js
  client/src/components/Common/Reviews/index.js
  client/src/components/Common/Section/Reviews.js
  client/src/components/Common/Section/Updates/SingleUpdate.js
  client/src/components/Common/Section/Wallet.js
  client/src/components/Common/Section/style.js
  client/src/components/Common/SingleReview/index.js
  client/src/components/Common/SingleReview/index.style.js
  client/src/components/Pages/Bookings/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/HostDashboard.style.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/HostDashboard/schemas.js
  client/src/components/Pages/HostDashboard/styleProperties.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/InternOrgView/index.js
  client/src/constants/apiRoutes.js
  client/src/helpers/formatPrice.js
  server/__test__/api/dashboard/host.js
  server/controllers/dashboard/hostDashboard.js
  server/controllers/listing/updateAvailability.js
  server/database/queries/bookings/getUpcomingBooking.js
  server/database/queries/dashboard/hostDashboard.js
  server/database/queries/listing/index.js
  server/database/queries/payments/getHostPaymentsInfo.js
  server/database/queries/profile/hostProfile.js
  server/database/queries/user/index.js
  server/middlewares/validation/hostDashboard.js
  server/middlewares/validation/index.js
  server/router/index.js
Labels: awaiting-review

#739 Admin Bursary Pages (Front End)
  client/src/components/Common/Figure/index.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/Inputs/Input.js
  client/src/components/Common/Inputs/style.js
  client/src/components/Common/Notification/index.js
  client/src/components/Common/Table/Common/ButtonCol.js
  client/src/components/Common/Table/Common/DropdownCol.js
  client/src/components/Common/Table/Common/InputCol.js
  client/src/components/Common/Table/Common/InterviewCol.js
  client/src/components/Common/Table/Common/StandardCol.js
  client/src/components/Common/Table/Common/index.js
  client/src/components/Common/Tabs/index.js
  client/src/components/Common/Typography/index.js
  client/src/components/Pages/Admin/AdminDashboard.style.js
  client/src/components/Pages/Admin/Bookings/BookingView/AdminActions.js
  client/src/components/Pages/Admin/Bookings/BookingView/Allocation.js
  client/src/components/Pages/Admin/Bookings/BookingView/BookingCancellationDetails.js
  client/src/components/Pages/Admin/Bookings/BookingView/BookingView.js
  client/src/components/Pages/Admin/Bookings/BookingView/Policy.js
  client/src/components/Pages/Admin/Bookings/BookingView/schema.js
  client/src/components/Pages/Admin/Bookings/BookingView/style.js
  client/src/components/Pages/Admin/Bookings/ExpandedDetails.js
  client/src/components/Pages/Admin/Bookings/columns.js
  client/src/components/Pages/Admin/Bookings/index.js
  client/src/components/Pages/Admin/Bursary/Response/Approve.js
  client/src/components/Pages/Admin/Bursary/Response/PreApprove.js
  client/src/components/Pages/Admin/Bursary/Response/Reject.js
  client/src/components/Pages/Admin/Bursary/Response/Success.js
  client/src/components/Pages/Admin/Bursary/Response/index.js
  client/src/components/Pages/Admin/Bursary/Response/style.js
  client/src/components/Pages/Admin/Bursary/Tables/Approved.js
  client/src/components/Pages/Admin/Bursary/Tables/History.js
  client/src/components/Pages/Admin/Bursary/Tables/PreApproved.js
  client/src/components/Pages/Admin/Bursary/Tables/Requests.js
  client/src/components/Pages/Admin/Bursary/Tables/index.js
  client/src/components/Pages/Admin/Bursary/Tables/renderExpandedSection.js
  client/src/components/Pages/Admin/Bursary/index.js
  client/src/components/Pages/Admin/ClientTable.js
  client/src/components/Pages/Admin/Dashboard/index.js
  client/src/components/Pages/Admin/HostTable.js
  client/src/components/Pages/Admin/InternTable.js
  client/src/components/Pages/Admin/Payments/PaymentTopStats.js
  client/src/components/Pages/Admin/Payments/PaymentsTable.js
  client/src/components/Pages/Admin/Payments/config.PaymentsTable.js
  client/src/components/Pages/Admin/Payments/paymentsSchema.js
  client/src/components/Pages/Admin/index.js
  client/src/components/Pages/index.js
  client/src/constants/bursaryOptions.js
  client/src/constants/navRoutes.js
  client/src/helpers/formatPrice.js
Labels: awaiting-review

#727 657 update home and create up funnel
  client/src/components/Common/Navigation/Menu.js
  client/src/components/Common/NotFound/index.js
  client/src/components/Common/Title/index.js
  client/src/components/Pages/SignUpFunnelPage/FunnelPageData.js
  client/src/components/Pages/SignUpFunnelPage/index.js
  client/src/components/Pages/SignUpFunnelPage/styled.js
  client/src/components/Pages/index.js
  client/src/constants/navRoutes.js
Labels: awaiting-review

#726 656 update log in
  client/src/components/Common/Inputs/Input.js
  client/src/components/Common/Inputs/style.js
  client/src/components/Layouts/LoginLayout/index.js
  client/src/components/Layouts/LoginLayout/style.js
  client/src/components/Layouts/index.js
  client/src/components/Pages/SignInPage/SignInPage.style.js
  client/src/components/Pages/SignInPage/index.js
  client/src/components/Pages/index.js
Labels: approved

#732 708 709 intern setting
  client/src/components/Common/Inputs/DatePicker.js
  client/src/components/Common/Inputs/Input.js
  client/src/components/Common/Inputs/Select.js
  client/src/components/Common/Inputs/UploadFile.js
  client/src/components/Common/Inputs/style.js
  client/src/components/Common/Navigation/Menu.js
  client/src/components/Common/Notification/index.js
  client/src/components/Common/Typography/style.js
  client/src/components/Pages/Bookings/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostProfile/InternOrgView/index.js
  client/src/components/Pages/Settings/AboutMe.js
  client/src/components/Pages/Settings/DeleteAccount.js
  client/src/components/Pages/Settings/MyAccount.js
  client/src/components/Pages/Settings/MyProfile.js
  client/src/components/Pages/Settings/UnderReview.js
  client/src/components/Pages/Settings/Verifications.js
  client/src/components/Pages/Settings/index.js
  client/src/components/Pages/Settings/style.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/errorMessages.js
  client/src/constants/externalLinks.js
  client/src/constants/navRoutes.js
  client/src/constants/types.js
  client/src/helpers.js
  client/src/validation/index.js
  client/src/validation/internSettings.js
  server/controllers/user/internSettings/aboutMe.js
  server/controllers/user/internSettings/index.js
  server/controllers/user/internSettings/myAccount.js
  server/controllers/user/internSettings/myProfile.js
  server/controllers/user/internSettings/verifications.js
  server/database/constants.js
  server/database/data/test/profiles.js
  server/database/models/Profile.js
  server/database/queries/bookings/getUpcomingBooking.js
  server/database/queries/profile/hostProfile.js
  server/router/index.js
Labels: awaiting-review

#725 705 update add funds
  client/package-lock.json
  client/package.json
  client/src/components/Common/Grid/style.js
  client/src/components/Common/Icon/icons/UnKnownCard.js
  client/src/components/Common/Icon/index.js
  client/src/components/Common/Inputs/Input.js
  client/src/components/Common/Inputs/StripeInput.js
  client/src/components/Common/Inputs/index.js
  client/src/components/Common/Title/WithBackground.js
  client/src/components/Common/Title/index.js
  client/src/components/Layouts/RightDivLayout/style.js
  client/src/components/Pages/OrgDashboard/AddFunds/index.js
  client/src/components/Pages/OrgDashboard/AddFunds/style.js
  client/src/components/Pages/OrgDashboard/AddFunds/validationSchema.js
  client/src/components/Pages/OrgDashboard/AddFundsModal.js
  client/src/components/Pages/OrgDashboard/AddFundsModal.style.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/SignInPage/index.js
  client/src/components/Pages/SignUpFunnelPage/index.js
  client/src/components/Pages/SignUpFunnelPage/styled.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/errorMessages.js
  client/src/constants/navRoutes.js
  client/src/stories/9-Title.stories.js
  server/controllers/payments/organisation.js
  server/controllers/user/accountInfo.js
  server/database/queries/account/index.js
  server/router/index.js
Labels: approved

#740 Update Organisation Model
  server/database/data/test/organisations.js
  server/database/models/Organisation.js
Labels: awaiting-review

#734 Fix client vulnerabilities
  client/package-lock.json
  client/package.json
Labels: awaiting-review

#745 687 admin bursary backend
  client/src/components/Common/Inputs/DatePicker.js
  client/src/components/Common/Inputs/Select.js
  client/src/components/Common/Navigation/Menu.js
  client/src/components/Common/Table/Common/InputCol.js
  client/src/components/Common/Table/Common/InterviewCol.js
  client/src/components/Common/Table/Common/StandardCol.js
  client/src/components/Common/Table/index.js
  client/src/components/Common/Tabs/index.js
  client/src/components/Pages/Admin/Bursary/Response/Approve.js
  client/src/components/Pages/Admin/Bursary/Response/PreApprove.js
  client/src/components/Pages/Admin/Bursary/Response/Reject.js
  client/src/components/Pages/Admin/Bursary/Response/Success.js
  client/src/components/Pages/Admin/Bursary/Tables/Approved.js
  client/src/components/Pages/Admin/Bursary/Tables/History.js
  client/src/components/Pages/Admin/Bursary/Tables/PreApproved.js
  client/src/components/Pages/Admin/Bursary/Tables/Requests.js
  client/src/components/Pages/Admin/Bursary/Tables/renderExpandedSection.js
  client/src/components/Pages/Admin/Bursary/index.js
  client/src/components/Pages/Admin/Bursary/utils.js
  client/src/components/Pages/Admin/Bursary/validationSchema.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  client/src/helpers.js
  server/__test__/api/bursary/bursaryApplications.js
  server/__test__/api/bursary/bursaryWindows.js
  server/controllers/bursary/approveBursaryApplication.js
  server/controllers/bursary/editBursary.js
  server/controllers/bursary/getBursary.js
  server/controllers/bursary/getMyBursary.js
  server/controllers/bursary/index.js
  server/database/constants.js
  server/database/data/resetDB.js
  server/database/data/test/bursaries.js
  server/database/data/test/bursaryApplications.js
  server/database/data/test/bursaryWindows.js
  server/database/data/test/index.js
  server/database/data/test/profiles.js
  server/database/models/BursaryApplication.js
  server/database/models/BursaryWindow.js
  server/database/models/index.js
  server/database/queries/bursary/editBursary.js
  server/database/queries/bursary/getBursary.js
  server/database/queries/payments/approveBursaryApplication.js
  server/database/queries/payments/index.js
  server/database/queries/user/getUserByBursaryApplicationId.js
  server/database/queries/user/index.js
  server/pubSub/bursary.js
  server/pubSub/eventTypes.js
  server/pubSub/index.js
  server/router/index.js
  server/services/mailing/index.js
  server/services/mailing/sendBursaryEmails.js
  server/services/mailing/templates/intern/bursary.js
  server/services/mailing/templates/intern/index.js
  server/services/mailing/templates/mailsTypes.js
Labels: awaiting-review

#735 Create footer
  client/src/components/Common/Footer/Footer.style.js
  client/src/components/Common/Footer/index.js
  client/src/components/Common/FooterNew/index.js
  client/src/components/Common/FooterNew/style.js
  client/src/components/Common/Route/index.js
  client/src/components/Layouts/GeneralLayout/index.js
  client/src/components/Layouts/GeneralLayout/style.js
  client/src/components/Layouts/SideMenuLayout/index.js
  client/src/components/Pages/index.js
  client/src/constants/externalLinks.js
Labels: request-changes

#723 653 create get started sections
  client/src/components/Common/ProgressBar/index.js
  client/src/components/Common/ProgressBar/styled.js
  client/src/components/Common/Title/index.js
  client/src/components/Layouts/IllustrationsLayout/index.js
  client/src/components/Layouts/IllustrationsLayout/style.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/SignInPage/SignInPage.style.js
  client/src/components/Pages/SignInPage/index.js
  client/src/components/Pages/SignUpFunnelPage/index.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/components/Pages/WelcomePages/Welcome.js
  client/src/components/Pages/WelcomePages/index.js
  client/src/components/Pages/WelcomePages/styled.js
  client/src/components/Pages/WelcomePages/welcomeContent.js
  client/src/components/Pages/WelcomePages/wlcomeImage.js
  client/src/components/Pages/index.js
  client/src/constants/navRoutes.js
Labels: awaiting-review

#743 Org Dashboard and Add Coupon Updates
  client/src/components/Common/CouponCode/index.js
  client/src/components/Common/Inputs/DatePicker.js
  client/src/components/Common/Section/AccountDetails.js
  client/src/components/Common/Section/Coupons.js
  client/src/components/Common/Section/MyAccount.js
  client/src/components/Common/Section/Updates/SingleUpdate.js
  client/src/components/Common/Section/Updates/index.js
  client/src/components/Common/Section/index.js
  client/src/components/Common/Section/style.js
  client/src/components/Common/Table/Common/StandardCol.js
  client/src/components/Common/Table/index.js
  client/src/components/Pages/BookingView/InternView/MakePayment/index.js
  client/src/components/Pages/BookingView/InternView/PaymentsPlan.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/BookingView/helpers.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/InternOrgView/index.js
  client/src/components/Pages/HostProfile/old_index.js
  client/src/components/Pages/OrgDashboard/AddCoupons/Form.js
  client/src/components/Pages/OrgDashboard/AddCoupons/index.js
  client/src/components/Pages/OrgDashboard/AddCoupons/style.js
  client/src/components/Pages/OrgDashboard/AddCoupons/validationSchema.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/CouponsColumns.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
  client/src/components/Pages/OrgDashboard/index.js
  client/src/components/Pages/OrgDashboard/styleProperties.js
  client/src/components/Pages/OrgDashboard/utils.js
  client/src/components/Pages/index.js
  client/src/constants/navRoutes.js
  client/src/helpers.js
  server/__test__/api/orgPaymentsAndCoupons/createCoupon.js
  server/controllers/coupon/getCoupons.js
  server/controllers/coupon/getCouponsSoft.js
  server/controllers/coupons/createCoupon.js
  server/controllers/dashboard/index.js
  server/controllers/dashboard/orgDashboard.js
  server/database/models/Coupon.js
  server/database/queries/dashboard/index.js
  server/database/queries/dashboard/orgDashboard.js
  server/database/queries/payments/createCoupon.js
  server/database/queries/user/index.js
  server/database/queries/user/organisation.js
  server/helpers/createDatesArray.js
  server/helpers/payments.js
  server/pubSub/coupon.js
  server/pubSub/eventTypes.js
  server/pubSub/index.js
  server/router/index.js
  server/services/mailing/couponCreated.js
  server/services/mailing/index.js
  server/services/mailing/templates/mailsTypes.js
  server/services/mailing/templates/organisation/couponCreated.js
  server/services/mailing/templates/organisation/index.js
Labels: awaiting-review

#755 700 update organisation singup
  client/src/components/Common/Inputs/Input.js
  client/src/components/Common/Route/index.js
  client/src/components/Common/Title/WithBackground.js
  client/src/components/Layouts/SignupLayout/OrganisationSteps.js
  client/src/components/Layouts/SignupLayout/index.js
  client/src/components/Layouts/SignupLayout/style.js
  client/src/components/Pages/InternSignUpFlow/Verifications.js
  client/src/components/Pages/OrgDashboard/AddFunds/index.js
  client/src/components/Pages/OrgSignUpFlow/AccountDetails/index.js
  client/src/components/Pages/OrgSignUpFlow/CreateProfile/index.js
  client/src/components/Pages/OrgSignUpFlow/Welcome/index.js
  client/src/components/Pages/OrgSignUpFlow/index.js
  client/src/components/Pages/OrgSignUpFlow/style.js
  client/src/components/Pages/SignUpPage/SignUp.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  client/src/helpers.js
  client/src/validation/index.js
  client/src/validation/orgSignup.js
  client/src/validation/signup.js
  server/__test__/api/users/signup.js
  server/controllers/organisation/getOrgDetails.js
  server/controllers/organisation/updateOrgDetails.js
  server/controllers/user/signup.js
  server/database/data/test/organisations.js
  server/database/models/Organisation.js
  server/database/queries/organisation/getOrgDetails.js
  server/database/queries/organisation/updateOrgDetails.js
  server/router/index.js
Labels: awaiting-review

#754 682 bursary intern
  client/src/components/Common/FAQ/index.js
  client/src/components/Common/FAQ/style.js
  client/src/components/Common/Inputs/Select.js
  client/src/components/Common/Typography/style.js
  client/src/components/Pages/Bursary/Application.js
  client/src/components/Pages/Bursary/Success.js
  client/src/components/Pages/Bursary/index.js
  client/src/components/Pages/Bursary/style.js
  client/src/components/Pages/InternSignUpFlow/MyProfile.js
  client/src/components/Pages/InternSignUpFlow/Verifications.js
  client/src/components/Pages/Settings/Intern/MyProfile.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  client/src/constants/navRoutes.js
  client/src/validation/index.js
  client/src/validation/internBursary.js
  client/src/validation/internCompleteProfile.js
  server/controllers/bursary/createBursaryApp.utils.js
  server/controllers/bursary/editBursary.js
  server/controllers/bursary/getBursary.js
  server/controllers/user/internSettings/aboutMe.js
  server/controllers/user/internSettings/myProfile.js
  server/controllers/user/internSettings/verifications.js
  server/database/data/test/bursaryApplications.js
  server/database/data/test/index.js
  server/database/models/BursaryApplication.js
  server/database/queries/bursary/createBursary.js
  server/database/queries/bursary/getBursary.js
  server/database/queries/bursary/index.js
  server/router/index.js
Labels: awaiting-review

#760 export bursary csv
  client/package-lock.json
  client/package.json
  client/src/components/Pages/Admin/Bursary/Tables/Approved.js
  client/src/components/Pages/Admin/Bursary/Tables/History.js
  client/src/components/Pages/Admin/Bursary/Tables/PreApproved.js
  client/src/components/Pages/Admin/Bursary/Tables/Requests.js
  client/src/components/Pages/Admin/Bursary/utils.js
  client/src/components/Pages/Admin/Clients/renderExpandedSection.js
  client/src/components/Pages/InternDashboard/index.js
  client/src/components/Pages/index.js
  client/src/constants/navRoutes.js
  server/controllers/bursary/getBursary.js
  server/database/data/createEmptyCollection.js
  server/database/data/production/index.js
  server/database/queries/bursary/getBursary.js
  server/database/queries/stats/getAllClientStats.js
Labels: awaiting-review

#762 Host fixes
  client/src/components/Common/Navigation/Menu.js
  client/src/components/Common/Navigation/SideMenu/index.js
  client/src/components/Common/Route/index.js
  client/src/components/Layouts/SideMenuLayout/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostProfile/InternOrgView/Header.js
  client/src/components/Pages/HostProfile/InternOrgView/HostProfileCalendar.js
  client/src/components/Pages/HostProfile/InternOrgView/index.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/InternView.js
Labels: awaiting-review
