Repository yalla-coop/presspad, pull requests merged in 2020-01, with the labels that each got.

#264 Create checklists for host and intern
  client/package-lock.json
  client/src/components/Common/Checklist/Checkbox.js
  client/src/components/Common/Checklist/Checklist.style.js
  client/src/components/Common/Checklist/HintText.js
  client/src/components/Common/Checklist/index.js
  client/src/components/Pages/BookingView/index.js
  client/src/constants/apiRoutes.js
  client/src/helpers/getAbsoluteLink.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/config.js
  server/controllers/booking/acceptBooking.js
  server/controllers/booking/viewBooking.js
  server/controllers/checklist/updateChecklistAnswer.js
  server/database/data/development/checklistQuestions.js
  server/database/data/resetDB.js
  server/database/models/ChecklistAnswer.js
  server/database/models/ChecklistQuestion.js
  server/database/models/index.js
  server/database/queries/bookings/getBookingById.js
  server/database/queries/checkList/createChecklistAnswers.js
  server/database/queries/checkList/index.js
  server/database/queries/checkList/updateChecklistAnswer.js
  server/helpers/addLinksIntoQuestion.js
  server/helpers/createBookingChecklistAnswers.js
  server/helpers/mailHelper/index.js
  server/router/index.js
Labels: awaiting-review

#268 give badge to host after finishing first hosting
  server/app.js
  server/database/dbConnection.js
  server/database/queries/profile/profileBadge.js
  server/helpers/cronjobs/giveBadges/index.js
  server/helpers/cronjobs/index.js
Labels: awaiting-review

#267 Create a notification for hosts on new requests
  client/src/components/Common/Update/index.js
  server/controllers/booking/newBookingRequest.js
Labels: awaiting-review

#269 Fix calculating price bug
  client/src/components/Pages/HostProfile/Calendar.js
  server/__test__/api/newBooking.js
  server/controllers/booking/newBookingRequest.js
  server/database/queries/profile/profileBadge.js
Labels: awaiting-review

#276 fix booking table links
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/TablesColumns.js
  client/src/components/Pages/InternDashboard/TablesColumns.js
Labels: awaiting-review

#273 admin checklist email
  server/__test__/database/schema/scheduledEmails.js
  server/controllers/booking/acceptBooking.js
  server/database/data/development/checklistQuestions.js
  server/database/data/development/scheduledEmails.js
  server/database/data/test/scheduledEmails.js
  server/database/models/ScheduledEmail.js
  server/database/queries/ScheduledEmail/createScheduledEmails.js
  server/database/queries/ScheduledEmail/getOutstandingReminders.js
  server/database/queries/ScheduledEmail/index.js
  server/helpers/addLinksIntoQuestion.js
  server/helpers/cronjobs/index.js
  server/helpers/cronjobs/sendScheduledReminders/index.js
  server/helpers/mailHelper/checklistReminders/createChecklistArray.js
  server/helpers/mailHelper/checklistReminders/emailBodyToAdmin.js
  server/helpers/mailHelper/checklistReminders/emailBodyToInternAndHost.js
  server/helpers/mailHelper/checklistReminders/generateListRow.js
  server/helpers/mailHelper/checklistReminders/index.js
  server/helpers/mailHelper/checklistReminders/toAdmin.js
  server/helpers/mailHelper/checklistReminders/toHostAndIntern.js
  server/helpers/mailHelper/index.js
  server/services/mailing/index.js
  server/services/mailing/markScheduledEmailsAsSent.js
  server/services/mailing/scheduleReminderEmails.js
  server/services/mailing/sendOutstandingReminders.js
Labels: awaiting-review

#275 redirect to profile if intern has no profile
  client/src/components/Pages/HostProfile/Calendar.js
Labels: awaiting-review

#278 Cron job: return the reserved money in the coupons when they get expired
  server/database/data/development/coupons.js
  server/database/data/test/coupons.js
  server/database/models/Coupon.js
  server/database/queries/account/index.js
  server/database/queries/coupon/index.js
  server/database/queries/payments/couponTransactions.js
  server/database/queries/payments/createCoupon.js
  server/database/transactionWrapper.js
  server/helpers/cronjobs/index.js
  server/helpers/cronjobs/releaseExpiredCouponsValue/index.js
  server/services/coupon/index.js
  server/services/coupon/releaseExpiredCouponsValue.js
Labels: awaiting-review

#297 Create Tabs common component
  client/src/components/Common/TabbedView/TabbedView.style.js
  client/src/components/Common/TabbedView/index.js
Labels: awaiting-review

#277 payment reminders
  server/controllers/payments/intern.js
  server/database/models/ScheduledEmail.js
  server/database/queries/ScheduledEmail/createScheduledEmails.js
  server/database/queries/ScheduledEmail/getOutstandingPaymentReminders.js
  server/database/queries/ScheduledEmail/index.js
  server/database/queries/ScheduledEmail/markScheduledEmailsAsSent.js
  server/helpers/cronjobs/index.js
  server/helpers/cronjobs/sendScheduledPaymentReminders/index.js
  server/helpers/mailHelper/sendPaymentReminderToIntern.js
  server/services/mailing/index.js
  server/services/mailing/markScheduledEmailsAsSent.js
  server/services/mailing/schedulePaymentReminders.js
  server/services/mailing/sendOutstandingPaymentReminders.js
Labels: awaiting-review

#300 update host profile seen by Intern -back-end
  server/database/models/Profile.js
  server/database/queries/profile/hostProfile.js
Labels: awaiting-review

#306 Create Coupon Bugfixes
  .vscode/settings.json
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/CouponsColumns.js
  client/src/components/Pages/OrgDashboard/index.js
  client/src/components/Pages/OrgDashboard/schema.js
  package.json
Labels: awaiting-review

#316 Fix profile listing model schema
  server/database/models/Listing.js
  server/database/models/Profile.js
Labels: awaiting-review

#315 Update host edit profile back end
  server/app.js
  server/controllers/hostsCompleteProfile.js
  server/middlewares/validation/hostProfileSchema.js
  server/middlewares/validation/index.js
Labels: awaiting-review

#308 280 intern edit profile
  client/src/components/Common/ProfileComponents/AboutYouDetails/index.js
  client/src/components/Common/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Common/ProfileComponents/Demographic/index.js
  client/src/components/Common/ProfileComponents/Field/DatePicker.js
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Common/ProfileComponents/Field/Input.js
  client/src/components/Common/ProfileComponents/Field/Select.js
  client/src/components/Common/ProfileComponents/Field/YesNoRadio.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Common/ProfileComponents/OtherInformationDetails/index.js
  client/src/components/Common/ProfileComponents/OtherInformationProfile/index.js
  client/src/components/Common/ProfileComponents/ProfileComponents.style.js
  client/src/components/Common/ProfileComponents/Title.js
  client/src/components/Common/ProfileComponents/index.js
  client/src/components/Common/TabbedView/TabbedView.style.js
  client/src/components/Common/TabbedView/index.js
  client/src/components/Pages/InternCreateProfile/Content copy.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/HeaderWrapper.js
  client/src/components/Pages/InternCreateProfile/InternCreateProfile.style.js
  client/src/components/Pages/InternCreateProfile/index copy.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/constants/fields.js
  client/src/constants/types.js
  server/controllers/user/internsCompleteProfile.js
  server/middlewares/validation/index.js
  server/middlewares/validation/internCompleteProfileSchema.js
  server/middlewares/validation/internProfileSchema.js
Labels: awaiting-review

#307 Refactor SignUp
  client/public/index.html
  client/src/components/Pages/SignUpPage/SignUp.js
  client/src/components/Pages/SignUpPage/SignUpPage.style.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/constants/navRoutes.js
  client/src/theme.js
  server/database/dbConnection.js
Labels: awaiting-review

#303 Booking view
  client/src/components/Common/Checklist/index.js
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/BookingView/BookingInfo.js
  client/src/components/Pages/BookingView/BookingRequestSection/bookingRequestSection.style.js
  client/src/components/Pages/BookingView/BookingRequestSection/index.js
  client/src/components/Pages/BookingView/PaymentsPlan.js
  client/src/components/Pages/BookingView/index.js
  client/src/components/Pages/InternProfile/HostView/HostView.style.js
  client/src/components/Pages/InternProfile/HostView/index.js
  client/src/components/Pages/InternProfile/HostView/questions.json
  client/src/components/Pages/InternProfile/index.js
  server/database/data/development/checklistQuestions.js
  server/database/queries/bookings/getBookingById.js
Labels: awaiting-review

#325 fix uploading bug
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/index.js
  client/src/constants/fields.js
  server/controllers/profile/getInternProfile.js
  server/controllers/user/internsCompleteProfile.js
Labels: awaiting-review

#319 prepare the layout for the host view of the intern profile
  client/src/components/Pages/InternProfile/HostView/HostView.style.js
  client/src/components/Pages/InternProfile/HostView/index.js
  server/middlewares/validation/internCompleteProfileSchema.js
Labels: awaiting-review

#327 Pre-fill intern's profile data
  client/package-lock.json
  client/src/components/Common/ProfileComponents/Field/DatePicker.js
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Common/ProfileComponents/Field/Select.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/index.js
  package-lock.json
  package.json
  server/controllers/profile/getMyProfile.js
Labels: awaiting-review

#330 Update intern edit profile backend
  package-lock.json
  package.json
  server/database/models/Profile.js
  server/middlewares/validation/hostDashboard.js
  server/middlewares/validation/hostProfileSchema.js
  server/middlewares/validation/index.js
  server/middlewares/validation/internCompleteProfileSchema.js
  server/middlewares/validation/internProfileSchema.js
  server/middlewares/validation/wordLengthValidator.js
Labels: awaiting-review

#329 Remove Repetition
  client/src/components/Pages/HostDashboard/Content.js
Labels: awaiting-review

#321 284 update host profile
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/HostProfile/index.js
  client/src/helpers.js
Labels: awaiting-review

#335 Bug Fix In View Booking
  client/src/components/Pages/InternDashboard/BookingsTableSection.js
Labels: awaiting-review

#331 updated intern profile view for the admin
  client/src/components/Common/ProfileComponents/AboutYouDetails/index.js
  client/src/components/Common/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Common/ProfileComponents/Demographic/index.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Common/ProfileComponents/OtherInformationProfile/index.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/AdminView.js
  client/src/components/Pages/InternProfile/AdminOrInternView/InternProfile.style.js
  client/src/components/Pages/InternProfile/AdminOrInternView/InternView.js
  client/src/components/Pages/InternProfile/AdminOrInternView/index.js
  client/src/components/Pages/index.js
  client/src/constants/apiRoutes.js
  package-lock.json
  server/controllers/profile/getMyProfile.js
  server/controllers/stats/adminStats.js
  server/router/index.js
Labels: awaiting-review

#320 registered a cron to delete old bookings that their start date has passed
  server/database/queries/bookings/getOldBookings.js
  server/helpers/cronjobs/cancelOldBookings/index.js
  server/helpers/cronjobs/index.js
Labels: awaiting-review

#334 Bugfixes simon
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/LandingPage/index.js
  server/controllers/booking/newBookingRequest.js
Labels: awaiting-review

#338 Fixed View Less Bug In Host
  client/src/components/Pages/HostDashboard/index.js
Labels: awaiting-review

#341 Fix links buttons
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Common/Update/index.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/InternProfile/HostView/index.js
Labels: awaiting-review

#342 search bug
  client/src/components/Common/Button/index.js
  client/src/components/Pages/SearchHosts/SearchHosts.style.js
  client/src/components/Pages/SearchHosts/index.js
  client/src/constants/types.js
  server/controllers/hostsCompleteProfile.js
  server/controllers/profile/searchProfiles.js
  server/database/constants.js
  server/database/models/Listing.js
  server/database/models/Profile.js
  server/database/queries/listing/index.js
  server/database/queries/profile/searchProfiles.js
Labels: awaiting-review

#348 admin view fields style
  client/src/components/Common/ProfileComponents/AboutYouDetails/index.js
  client/src/components/Common/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Common/ProfileComponents/Demographic/index.js
  client/src/components/Common/ProfileComponents/Field/Checkist.js
  client/src/components/Common/ProfileComponents/Field/DatePicker.js
  client/src/components/Common/ProfileComponents/Field/DateRanges.js
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Common/ProfileComponents/Field/Input.js
  client/src/components/Common/ProfileComponents/Field/Select.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Common/ProfileComponents/OtherInformationDetails/index.js
  client/src/components/Common/ProfileComponents/OtherInformationProfile/index.js
  client/src/components/Common/ProfileComponents/ProfileComponents.style.js
  client/src/components/Pages/OrgDashboard/CouponsColumns.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
Labels: awaiting-review

#337 Improve Mobile Responsiveness
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/App.js
  client/src/components/Common/Navbar/Menu.js
  client/src/components/Common/Navbar/index.js
  client/src/components/Common/Profile/ListingGallery.js
  client/src/components/Common/Profile/ListingGallery.style.js
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Common/ProfileComponents/AboutYouDetails/index.js
  client/src/components/Common/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Common/ProfileComponents/Demographic/index.js
  client/src/components/Common/ProfileComponents/Field/Checkist.js
  client/src/components/Common/ProfileComponents/Field/DateRanges.js
  client/src/components/Common/ProfileComponents/Field/Input.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Common/ProfileComponents/OtherInformationDetails/index.js
  client/src/components/Common/ProfileComponents/ProfileComponents.style.js
  client/src/components/Common/TabbedView/TabbedView.style.js
  client/src/components/Common/general/index.js
  client/src/components/Pages/HostCreateProfile/HeaderWrapper.js
  client/src/components/Pages/HostCreateProfile/HostCreateProfile.style.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/AboutYouDetails/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/Demographic/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/Details/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/OfferDetails/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/OtherInformation/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/Title.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/InternCreateProfile/Content.js
  client/src/components/Pages/InternCreateProfile/HeaderWrapper.js
  client/src/components/Pages/InternCreateProfile/InternCreateProfile.style.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/InternDashboard/BookingSection.js
  client/src/components/Pages/InternProfile/AdminOrInternView/InternProfile.style.js
  client/src/components/Pages/InternProfile/AdminOrInternView/InternView.js
  client/src/components/Pages/InternProfile/AdminOrInternView/index.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
  client/src/components/Pages/SearchHosts/SearchHosts.style.js
  client/src/components/Pages/SearchHosts/index.js
  client/src/components/Pages/SignUpPage/SignUpPage.style.js
  client/src/components/Pages/index.js
  client/src/constants/screenWidths.js
  client/src/index.css
  client/src/theme.js
  package-lock.json
Labels: awaiting-review

#350 show error message for nested fields
  client/src/components/Common/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Common/ProfileComponents/Demographic/index.js
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Common/ProfileComponents/ProfileComponents.style.js
  client/src/components/Pages/InternCreateProfile/index.js
Labels: awaiting-review

#352 Intern Create Profile - not all transforms had .ensure() before
  client/src/components/Pages/InternCreateProfile/Schema.js
Labels: bug

#353 fix and validate public profile intern data
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/InternProfile/HostView/index.js
  client/src/components/Pages/InternProfile/index.js
  server/controllers/profile/hostViewInternProfile.js
  server/database/queries/profile/internPublicProfile.js
Labels: awaiting-review

#357 fix the missed columns in intern's booking table bug
  client/src/components/App.js
Labels: awaiting-review

#359 make interns verified by default
  server/controllers/user/internsCompleteProfile.js
  server/controllers/user/signup.js
  server/database/models/Profile.js
Labels: awaiting-review

#364 344 host create validation
  client/src/components/Pages/HostCreateProfile/Schema.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/constants/types.js
  package-lock.json
  package.json
Labels: awaiting-review

#360 Update the completed profiles validator schema
  client/src/components/Common/ProfileComponents/OtherInformationProfile/index.js
  client/src/constants/fields.js
  server/controllers/profile/getInternStatus.js
  server/middlewares/validation/internCompleteProfileSchema.js
Labels: awaiting-review

#370 Bug fixing
  .vscode/settings.json
  client/.eslintrc.js
  client/package-lock.json
  client/src/components/App.js
  client/src/components/Common/Footer/index.js
  client/src/components/Pages/Dashboard/index.js
  client/src/components/Pages/InternCreateProfile/Schema.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/components/Pages/SignUpPage/SignUp.js
  client/src/components/Pages/SignUpPage/index.js
  client/src/constants/externalLinks.js
  client/src/constants/fields.js
  client/src/constants/navRoutes.js
  client/src/theme.js
  package-lock.json
  server/config.js
Labels: awaiting-review

#373 Fix Back Links Bugs
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/AdminView.js
  client/src/components/Pages/InternProfile/HostView/index.js
Labels: awaiting-review

#365 Host profile
  client/src/components/App.js
  client/src/components/Common/Button/index.js
  client/src/components/Common/Profile/ListingGallery.js
  client/src/components/Pages/AdminDashboard/HostTable.js
  client/src/components/Pages/AdminDashboard/InternTable.js
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/Demographic/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/Details/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/OfferDetails/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/OtherInformation/index.js
  client/src/components/Pages/HostProfile/AdminView.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/HostView.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/HostProfile/index.js
  client/src/components/Pages/HostProfile/old_index.js
  client/src/components/Pages/InternProfile/AdminOrInternView/InternProfile.style.js
  client/src/components/Pages/SearchHosts/index.js
  client/src/constants/apiRoutes.js
  client/src/helpers.js
  client/src/helpers/getUserId.js
  server/controllers/profile/getMyProfile.js
  server/controllers/profile/verifyProfile.js
  server/controllers/stats/adminStats.js
  server/database/queries/profile/verifyProfile.js
  server/database/queries/stats/getAllHostStats.js
  server/router/index.js
Labels: awaiting-review

#372 Make The Header Mobile Friendly
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/BookingView/index.js
  client/src/components/Pages/HostProfile/Profile.style.js
  server/database/constants.js
Labels: awaiting-review

#377 Make Booking Request Responsive
  client/src/components/Common/DisabledPopOver/DisabledPopOver.style.js
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/BookingView/PaymentsPlan.style.js
  client/src/components/Pages/BookingView/index.js
Labels: awaiting-review

#378 Intern create profile bugfixing and improvements
  .vscode/settings.json
  client/public/index.html
  client/src/components/Common/ProfileComponents/Field/Input.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Common/ProfileComponents/ProfileComponents.style.js
  client/src/components/Pages/HostCreateProfile/Schema.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/InternCreateProfile/Schema.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/constants/fields.js
  client/src/helpers.js
  server/middlewares/validation/hostProfileSchema.js
  server/middlewares/validation/internProfileSchema.js
Labels: awaiting-review

#371 Host profile backend
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/HostProfile/Profile.style.js
  server/controllers/profile/getHostProfile.js
  server/database/models/Profile.js
  server/database/queries/profile/hostProfile.js
  server/helpers/isValidMongoObjectId.js
  server/router/index.js
Labels: awaiting-review

#362 refactor bookingView
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Common/general/index.js
  client/src/components/Pages/BookingView/BookingRequestSection/index.js
  client/src/components/Pages/BookingView/Checklist/Checkbox.js
  client/src/components/Pages/BookingView/Checklist/Checklist.style.js
  client/src/components/Pages/BookingView/Checklist/HintText.js
  client/src/components/Pages/BookingView/Checklist/index.js
  client/src/components/Pages/BookingView/HostView/HostView.style.js
  client/src/components/Pages/BookingView/HostView/InternInfo.js
  client/src/components/Pages/BookingView/HostView/index.js
  client/src/components/Pages/BookingView/InternView/BookingInfo.js
  client/src/components/Pages/BookingView/InternView/CouponCode.js
  client/src/components/Pages/BookingView/InternView/PayNowModal.js
  client/src/components/Pages/BookingView/InternView/PaymentsPlan.js
  client/src/components/Pages/BookingView/InternView/PaymentsPlan.style.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/BookingView/index.js
  client/src/constants/apiRoutes.js
  server/controllers/booking/viewBooking.js
  server/controllers/checklist/getChecklist.js
  server/controllers/checklist/index.js
  server/controllers/profile/hostViewInternProfile.js
  server/database/queries/bookings/getBooking.js
  server/database/queries/bookings/index.js
  server/database/queries/checkList/getChecklistForUser.js
  server/database/queries/checkList/index.js
  server/router/index.js
Labels: awaiting-review

#380 fix request button
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/InternOrgView.js
Labels: awaiting-review

#376 create build production schema script
  package.json
  server/database/data/createEmptyCollection.js
  server/database/data/production/accounts.js
  server/database/data/production/checklistQuestions.js
  server/database/data/production/index.js
  server/database/data/production/resetDb.js
  server/database/data/production/users.js
Labels: awaiting-review

#374 310 > host search responsiveness
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/HostProfile/Calendar.js
  client/src/components/Pages/HostProfile/Calendar.style.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/SearchHosts/SearchHosts.style.js
  client/src/components/Pages/SearchHosts/index.js
Labels: awaiting-review

#388 fixed login error messages in the frontend
  client/src/components/Pages/SignInPage/SignInPage.style.js
  client/src/components/Pages/SignInPage/index.js
Labels: awaiting-review

#389 Update demographics
  client/src/components/Common/ProfileComponents/Demographic/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/Demographic/index.js
  client/src/constants/fields.js
  client/src/constants/types.js
  server/database/constants.js
Labels: awaiting-review

#391 Fix Undefined Values
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/HostProfile/InternOrgView.js
Labels: awaiting-review

#386 Fix bugs general
  client/src/assets/logo-placeholder.png
  client/src/components/Common/DisabledPopOver/DisabledPopOver.style.js
  client/src/components/Common/DisabledPopOver/index.js
  client/src/components/Common/Navbar/Menu.js
  client/src/components/Common/ProfileComponents/Field/DateRanges.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/OfferDetails/index.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/index.js
  client/src/components/Pages/SignUpPage/SignUpPage.style.js
  server/middlewares/validation/hostProfileSchema.js
Labels: awaiting-review

#387 Make Request Booking Responsive
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Pages/BookingView/BookingRequestSection/bookingRequestSection.style.js
  client/src/components/Pages/BookingView/HostView/HostView.style.js
  client/src/components/Pages/BookingView/HostView/InternInfo.js
  client/src/components/Pages/BookingView/HostView/index.js
  client/src/components/Pages/BookingView/InternView/index.js
Labels: awaiting-review

#403 Mail complete your profile link typo > #397
  server/helpers/mailHelper/profileApprovedToHost.js
Labels: awaiting-review

#404 made `my-profile` return InternCreateProfile
  client/src/components/Pages/MyProfile/index.js
Labels: awaiting-review

#384 Notifications and updates
  client/src/components/Common/Update/index.js
  client/src/components/Pages/BookingView/HostView/InternInfo.js
  server/controllers/booking/acceptBooking.js
  server/controllers/booking/newBookingRequest.js
  server/controllers/booking/rejectBooking.js
  server/controllers/dashboard/internDashboard.js
  server/controllers/review/index.js
  server/database/models/Booking.js
  server/database/models/Notification.js
  server/database/queries/bookings/getCompletedBookings.js
  server/database/queries/bookings/getHostNextBooking.js
  server/database/queries/bookings/getInternNextBooking.js
  server/database/queries/bookings/markBookingsCompleted.js
  server/database/queries/notification/index.js
  server/database/queries/organisation/dashboard.js
  server/database/queries/profile/hostProfile.js
  server/database/queries/stats/getAllHostStats.js
  server/database/queries/stats/getAllInternStats.js
  server/database/queries/user/index.js
  server/helpers/cronjobs/completeBookingsAndNotify/index.js
  server/helpers/cronjobs/index.js
  server/services/notifications/index.js
  server/services/notifications/registerNotification.js
Labels: awaiting-review

#414 fixed table header for payments tab in the admin dashboard
  client/src/components/Pages/AdminDashboard/index.js
Labels: awaiting-review

#413 fixed images returned in the hosts search
  client/src/components/Pages/SearchHosts/index.js
  server/controllers/profile/searchProfiles.js
Labels: awaiting-review

#423 Update Sign In
  client/src/components/Pages/LandingPage/index.js
  client/src/components/Pages/SignInPage/SignInPage.style.js
  client/src/components/Pages/SignInPage/index.js
Labels: awaiting-review

#390 reviews section
  client/public/index.html
  client/src/components/Common/Reviews/Review.js
  client/src/components/Common/Reviews/Reviews.style.js
  client/src/components/Common/Reviews/index.js
  client/src/components/Pages/BookingView/HostView/index.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/InternProfile/HostView/index.js
  client/src/constants/apiRoutes.js
  server/controllers/review/getReviews.js
  server/controllers/review/index.js
  server/controllers/review/postReview.js
  server/database/queries/bookings/countCompletedBookingsByUser.js
  server/database/queries/bookings/index.js
  server/database/queries/review/getReviewsGiventToUser.js
  server/database/queries/review/index.js
  server/router/index.js
Labels: awaiting-review

#392 Make Host & Intern Dashboards Responsive
  client/src/components/Common/BookingSection/InternDashboard.style.js
  client/src/components/Common/BookingSection/index.js
  client/src/components/Common/Button/index.js
  client/src/components/Common/Calendar/Calendar.style.js
  client/src/components/Common/Calendar/index.js
  client/src/components/Common/general/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/HostDashboard.style.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/InternDashboard/BookingSection.js
  client/src/components/Pages/InternDashboard/BookingsTableSection.js
  client/src/components/Pages/InternDashboard/index.js
Labels: awaiting-review

#427 Update host view for intern profile
  client/src/components/Pages/InternProfile/HostView/index.js
Labels: awaiting-review, in-review

#412 Show More In Request Booking
  client/src/components/Common/BookingSection/index.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/HostProfile/InternOrgView.js
Labels: awaiting-review

#432 Missing label for completed status
  client/src/components/Pages/InternDashboard/TablesColumns.js
  client/src/theme.js
Labels: awaiting-review

#431 Schema more error
  client/src/components/Pages/HostCreateProfile/ProfileComponents/AboutYouProfile/index.js
  client/src/components/Pages/HostCreateProfile/Schema.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/InternCreateProfile/Schema.js
  client/src/components/Pages/InternCreateProfile/index.js
  client/src/constants/errorMessages.js
  client/src/constants/fields.js
  client/src/helpers.js
  server/database/constants.js
  server/middlewares/validation/hostProfileSchema.js
Labels: awaiting-review

#416 410 host address
  client/src/components/Common/Profile/Profiles.style.js
  client/src/components/Common/ProfileComponents/Field/index.js
  client/src/components/Pages/BookingView/InternView/index.js
  client/src/components/Pages/HostCreateProfile/ProfileComponents/OfferDetails/index.js
  client/src/components/Pages/HostCreateProfile/Schema.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/HostProfile/HostView.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/HostProfile/Profile.style.js
  client/src/components/Pages/SearchHosts/index.js
  client/src/constants/fields.js
  server/controllers/profile/getHostProfile.js
  server/controllers/profile/searchProfiles.js
  server/database/models/Listing.js
  server/database/queries/listing/index.js
  server/database/queries/profile/searchProfiles.js
  server/middlewares/validation/hostProfileSchema.js
Labels: awaiting-review

#426 small bugs
  client/src/components/Common/general/index.js
  client/src/components/Pages/BookingView/Checklist/index.js
  client/src/components/Pages/BookingView/HostView/InternInfo.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/InternDashboard/BookingSection.js
  client/src/components/Pages/SignInPage/index.js
  package.json
Labels: awaiting-review

#436 next quest: update host query to fetch only confirmed bookings
  server/database/queries/bookings/getHostNextBooking.js
Labels: awaiting-review

#434 handle files errors & disable date picker to pick 16 years before the current date
  client/src/components/Common/ProfileComponents/Field/DatePicker.js
  client/src/components/Common/ProfileComponents/Field/File.js
  client/src/components/Pages/HostCreateProfile/index.js
  client/src/components/Pages/InternCreateProfile/index.js
Labels: awaiting-review

#437 added payments table to host view of the booking
  client/src/components/Pages/BookingView/HostView/PaymentsTable.js
  client/src/components/Pages/BookingView/HostView/index.js
Labels: awaiting-review

#440 fix payment integer bug
  client/src/helpers.js
  server/controllers/payments/intern.js
  server/helpers/payments.js
Labels: awaiting-review

#433 Org tweaks
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/CouponsColumns.js
  client/src/constants/userTypes.js
Labels: awaiting-review

#439 add sqreen trackers
  package-lock.json
  package.json
  server/app.js
  server/controllers/user/login.js
  server/controllers/user/signup.js
  server/index.js
  server/middlewares/authentication.js
  server/middlewares/softAuthCheck.js
Labels: awaiting-review

#450 Bugs
  client/src/components/Common/Reviews/index.js
  client/src/components/Pages/SearchHosts/index.js
  server/controllers/stats/adminStats.js
  server/database/queries/stats/getAllInternStats.js
Labels: awaiting-review

#447 fix validation messages
  client/src/components/Pages/HostCreateProfile/Schema.js
  server/database/models/Listing.js
  server/middlewares/validation/hostProfileSchema.js
Labels: request-changes

#451 Fix org styling > #449 and #448
  client/src/components/Common/DisabledPopOver/DisabledPopOver.style.js
  client/src/components/Common/DisabledPopOver/index.js
  client/src/components/Pages/HostProfile/InternOrgView.js
  client/src/components/Pages/OrgDashboard/Content.js
  client/src/components/Pages/OrgDashboard/OrgDashboard.style.js
  client/src/helpers.js
  server/controllers/profile/getHostProfile.js
Labels: awaiting-review

#443 Fix host withdraw bugs
  client/src/components/Pages/AdminDashboard/index.js
  client/src/components/Pages/HostDashboard/Content.js
  client/src/components/Pages/HostDashboard/index.js
  client/src/components/Pages/HostDashboard/schemas.js
  server/controllers/dashboard/hostDashboard.js
  server/controllers/payments/index.js
  server/controllers/payments/withdrawRequest.js
  server/database/queries/dashboard/hostDashboard.js
  server/database/queries/payments/hostDonateToPresspad.js
  server/database/queries/payments/hostRequestToWithdrawMoney.js
Labels: awaiting-review

#453 escape characters in files names
  client/src/components/Common/ProfileComponents/Field/File.js
Labels: awaiting-review

#457 fix sqreen error
  server/index.js
  server/router/index.js
Labels: awaiting-review
